// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/market.proto

package marketpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceRequest) Reset() {
	*x = GetPriceRequest{}
	mi := &file_proto_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceRequest) ProtoMessage() {}

func (x *GetPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceRequest.ProtoReflect.Descriptor instead.
func (*GetPriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{0}
}

func (x *GetPriceRequest) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

type GetPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceResponse) Reset() {
	*x = GetPriceResponse{}
	mi := &file_proto_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceResponse) ProtoMessage() {}

func (x *GetPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceResponse.ProtoReflect.Descriptor instead.
func (*GetPriceResponse) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{1}
}

func (x *GetPriceResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GetAllTickersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTickersRequest) Reset() {
	*x = GetAllTickersRequest{}
	mi := &file_proto_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTickersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTickersRequest) ProtoMessage() {}

func (x *GetAllTickersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTickersRequest.ProtoReflect.Descriptor instead.
func (*GetAllTickersRequest) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{2}
}

type GetAllTickersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickers       []*Ticker              `protobuf:"bytes,1,rep,name=tickers,proto3" json:"tickers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTickersResponse) Reset() {
	*x = GetAllTickersResponse{}
	mi := &file_proto_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTickersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTickersResponse) ProtoMessage() {}

func (x *GetAllTickersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTickersResponse.ProtoReflect.Descriptor instead.
func (*GetAllTickersResponse) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllTickersResponse) GetTickers() []*Ticker {
	if x != nil {
		return x.Tickers
	}
	return nil
}

type Ticker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Change_24H    float64                `protobuf:"fixed64,5,opt,name=change_24h,json=change24h,proto3" json:"change_24h,omitempty"`
	Volume_24H    float64                `protobuf:"fixed64,6,opt,name=volume_24h,json=volume24h,proto3" json:"volume_24h,omitempty"`
	AssetType     string                 `protobuf:"bytes,7,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ticker) Reset() {
	*x = Ticker{}
	mi := &file_proto_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticker) ProtoMessage() {}

func (x *Ticker) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticker.ProtoReflect.Descriptor instead.
func (*Ticker) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{4}
}

func (x *Ticker) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *Ticker) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Ticker) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ticker) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Ticker) GetChange_24H() float64 {
	if x != nil {
		return x.Change_24H
	}
	return 0
}

func (x *Ticker) GetVolume_24H() float64 {
	if x != nil {
		return x.Volume_24H
	}
	return 0
}

func (x *Ticker) GetAssetType() string {
	if x != nil {
		return x.AssetType
	}
	return ""
}

var File_proto_market_proto protoreflect.FileDescriptor

const file_proto_market_proto_rawDesc = "" +
	"\n" +
	"\x12proto/market.proto\x12\x06market\"%\n" +
	"\x0fGetPriceRequest\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\"(\n" +
	"\x10GetPriceResponse\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\"\x16\n" +
	"\x14GetAllTickersRequest\"A\n" +
	"\x15GetAllTickersResponse\x12(\n" +
	"\atickers\x18\x01 \x03(\v2\x0e.market.TickerR\atickers\"\xbb\x01\n" +
	"\x06Ticker\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"change_24h\x18\x05 \x01(\x01R\tchange24h\x12\x1d\n" +
	"\n" +
	"volume_24h\x18\x06 \x01(\x01R\tvolume24h\x12\x1d\n" +
	"\n" +
	"asset_type\x18\a \x01(\tR\tassetType2\x9c\x01\n" +
	"\rMarketService\x12=\n" +
	"\bGetPrice\x12\x17.market.GetPriceRequest\x1a\x18.market.GetPriceResponse\x12L\n" +
	"\rGetAllTickers\x12\x1c.market.GetAllTickersRequest\x1a\x1d.market.GetAllTickersResponseB*Z(github.com/cryptox/shared/proto/marketpbb\x06proto3"

var (
	file_proto_market_proto_rawDescOnce sync.Once
	file_proto_market_proto_rawDescData []byte
)

func file_proto_market_proto_rawDescGZIP() []byte {
	file_proto_market_proto_rawDescOnce.Do(func() {
		file_proto_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_market_proto_rawDesc), len(file_proto_market_proto_rawDesc)))
	})
	return file_proto_market_proto_rawDescData
}

var file_proto_market_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_market_proto_goTypes = []any{
	(*GetPriceRequest)(nil),       // 0: market.GetPriceRequest
	(*GetPriceResponse)(nil),      // 1: market.GetPriceResponse
	(*GetAllTickersRequest)(nil),  // 2: market.GetAllTickersRequest
	(*GetAllTickersResponse)(nil), // 3: market.GetAllTickersResponse
	(*Ticker)(nil),                // 4: market.Ticker
}
var file_proto_market_proto_depIdxs = []int32{
	4, // 0: market.GetAllTickersResponse.tickers:type_name -> market.Ticker
	0, // 1: market.MarketService.GetPrice:input_type -> market.GetPriceRequest
	2, // 2: market.MarketService.GetAllTickers:input_type -> market.GetAllTickersRequest
	1, // 3: market.MarketService.GetPrice:output_type -> market.GetPriceResponse
	3, // 4: market.MarketService.GetAllTickers:output_type -> market.GetAllTickersResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_market_proto_init() }
func file_proto_market_proto_init() {
	if File_proto_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_market_proto_rawDesc), len(file_proto_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_market_proto_goTypes,
		DependencyIndexes: file_proto_market_proto_depIdxs,
		MessageInfos:      file_proto_market_proto_msgTypes,
	}.Build()
	File_proto_market_proto = out.File
	file_proto_market_proto_goTypes = nil
	file_proto_market_proto_depIdxs = nil
}
