// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deposits.sql

package sqlc

import (
	"context"
)

const countDepositsAdmin = `-- name: CountDepositsAdmin :one
SELECT count(*)
FROM deposits d
WHERE ($1::text = '' OR d.status = $1::text)
  AND ($2::text = '' OR EXISTS (
        SELECT 1 FROM users u WHERE u.id = d.user_id AND u.email ILIKE '%' || $2::text || '%'))
`

type CountDepositsAdminParams struct {
	Status string `json:"status"`
	Search string `json:"search"`
}

func (q *Queries) CountDepositsAdmin(ctx context.Context, arg CountDepositsAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDepositsAdmin, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDepositsByUser = `-- name: CountDepositsByUser :one
SELECT count(*) FROM deposits WHERE user_id = $1
`

func (q *Queries) CountDepositsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countDepositsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeposit = `-- name: CreateDeposit :one
INSERT INTO deposits (user_id, amount, amount_usdt, exchange_rate, currency, method, status, order_code, qr_code_url, sepay_ref)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, amount, amount_usdt, exchange_rate, currency, method, status, order_code, qr_code_url, sepay_ref, created_at, updated_at
`

type CreateDepositParams struct {
	UserID       int64   `json:"user_id"`
	Amount       float64 `json:"amount"`
	AmountUsdt   float64 `json:"amount_usdt"`
	ExchangeRate float64 `json:"exchange_rate"`
	Currency     string  `json:"currency"`
	Method       string  `json:"method"`
	Status       string  `json:"status"`
	OrderCode    string  `json:"order_code"`
	QrCodeUrl    string  `json:"qr_code_url"`
	SepayRef     string  `json:"sepay_ref"`
}

func (q *Queries) CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error) {
	row := q.db.QueryRow(ctx, createDeposit,
		arg.UserID,
		arg.Amount,
		arg.AmountUsdt,
		arg.ExchangeRate,
		arg.Currency,
		arg.Method,
		arg.Status,
		arg.OrderCode,
		arg.QrCodeUrl,
		arg.SepayRef,
	)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.AmountUsdt,
		&i.ExchangeRate,
		&i.Currency,
		&i.Method,
		&i.Status,
		&i.OrderCode,
		&i.QrCodeUrl,
		&i.SepayRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepositByID = `-- name: GetDepositByID :one
SELECT id, user_id, amount, amount_usdt, exchange_rate, currency, method, status, order_code, qr_code_url, sepay_ref, created_at, updated_at
FROM deposits
WHERE id = $1
`

func (q *Queries) GetDepositByID(ctx context.Context, id int64) (Deposit, error) {
	row := q.db.QueryRow(ctx, getDepositByID, id)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.AmountUsdt,
		&i.ExchangeRate,
		&i.Currency,
		&i.Method,
		&i.Status,
		&i.OrderCode,
		&i.QrCodeUrl,
		&i.SepayRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepositByOrderCode = `-- name: GetDepositByOrderCode :one
SELECT id, user_id, amount, amount_usdt, exchange_rate, currency, method, status, order_code, qr_code_url, sepay_ref, created_at, updated_at
FROM deposits
WHERE order_code = $1
`

func (q *Queries) GetDepositByOrderCode(ctx context.Context, orderCode string) (Deposit, error) {
	row := q.db.QueryRow(ctx, getDepositByOrderCode, orderCode)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.AmountUsdt,
		&i.ExchangeRate,
		&i.Currency,
		&i.Method,
		&i.Status,
		&i.OrderCode,
		&i.QrCodeUrl,
		&i.SepayRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDepositsAdmin = `-- name: ListDepositsAdmin :many
SELECT d.id, d.user_id, d.amount, d.amount_usdt, d.exchange_rate, d.currency, d.method, d.status, d.order_code, d.qr_code_url, d.sepay_ref, d.created_at, d.updated_at
FROM deposits d
WHERE ($1::text = '' OR d.status = $1::text)
  AND ($2::text = '' OR EXISTS (
        SELECT 1 FROM users u WHERE u.id = d.user_id AND u.email ILIKE '%' || $2::text || '%'))
ORDER BY d.created_at DESC
LIMIT $4 OFFSET $3
`

type ListDepositsAdminParams struct {
	Status string `json:"status"`
	Search string `json:"search"`
	Off    int32  `json:"off"`
	Lim    int32  `json:"lim"`
}

// Admin read model: optional status filter and optional free-text search on the
// owning user's email. An empty string disables the corresponding filter.
func (q *Queries) ListDepositsAdmin(ctx context.Context, arg ListDepositsAdminParams) ([]Deposit, error) {
	rows, err := q.db.Query(ctx, listDepositsAdmin,
		arg.Status,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deposit{}
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.AmountUsdt,
			&i.ExchangeRate,
			&i.Currency,
			&i.Method,
			&i.Status,
			&i.OrderCode,
			&i.QrCodeUrl,
			&i.SepayRef,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepositsByUser = `-- name: ListDepositsByUser :many
SELECT id, user_id, amount, amount_usdt, exchange_rate, currency, method, status, order_code, qr_code_url, sepay_ref, created_at, updated_at
FROM deposits
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDepositsByUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDepositsByUser(ctx context.Context, arg ListDepositsByUserParams) ([]Deposit, error) {
	rows, err := q.db.Query(ctx, listDepositsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deposit{}
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.AmountUsdt,
			&i.ExchangeRate,
			&i.Currency,
			&i.Method,
			&i.Status,
			&i.OrderCode,
			&i.QrCodeUrl,
			&i.SepayRef,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeposit = `-- name: UpdateDeposit :exec
UPDATE deposits
SET status = $2, amount_usdt = $3, exchange_rate = $4, qr_code_url = $5, sepay_ref = $6, updated_at = now()
WHERE id = $1
`

type UpdateDepositParams struct {
	ID           int64   `json:"id"`
	Status       string  `json:"status"`
	AmountUsdt   float64 `json:"amount_usdt"`
	ExchangeRate float64 `json:"exchange_rate"`
	QrCodeUrl    string  `json:"qr_code_url"`
	SepayRef     string  `json:"sepay_ref"`
}

// Persist the mutable fields after a state transition (Confirm/Fail) or once the
// bank reference is known.
func (q *Queries) UpdateDeposit(ctx context.Context, arg UpdateDepositParams) error {
	_, err := q.db.Exec(ctx, updateDeposit,
		arg.ID,
		arg.Status,
		arg.AmountUsdt,
		arg.ExchangeRate,
		arg.QrCodeUrl,
		arg.SepayRef,
	)
	return err
}
