// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Deposit struct {
	ID           int64     `json:"id"`
	UserID       int64     `json:"user_id"`
	Amount       float64   `json:"amount"`
	AmountUsdt   float64   `json:"amount_usdt"`
	ExchangeRate float64   `json:"exchange_rate"`
	Currency     string    `json:"currency"`
	Method       string    `json:"method"`
	Status       string    `json:"status"`
	OrderCode    string    `json:"order_code"`
	QrCodeUrl    string    `json:"qr_code_url"`
	SepayRef     string    `json:"sepay_ref"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type User struct {
	ID    int64  `json:"id"`
	Email string `json:"email"`
}

type Wallet struct {
	ID            int64     `json:"id"`
	UserID        int64     `json:"user_id"`
	Currency      string    `json:"currency"`
	Balance       float64   `json:"balance"`
	LockedBalance float64   `json:"locked_balance"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Withdrawal struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	Amount      float64   `json:"amount"`
	Currency    string    `json:"currency"`
	BankCode    string    `json:"bank_code"`
	BankAccount string    `json:"bank_account"`
	AccountName string    `json:"account_name"`
	Status      string    `json:"status"`
	AdminNote   string    `json:"admin_note"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
