// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CountDepositsAdmin(ctx context.Context, arg CountDepositsAdminParams) (int64, error)
	CountDepositsByUser(ctx context.Context, userID int64) (int64, error)
	CountWalletsByUser(ctx context.Context, userID int64) (int64, error)
	CountWithdrawalsAdmin(ctx context.Context, arg CountWithdrawalsAdminParams) (int64, error)
	CountWithdrawalsByUser(ctx context.Context, userID int64) (int64, error)
	CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error)
	CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) (Withdrawal, error)
	GetDepositByID(ctx context.Context, id int64) (Deposit, error)
	GetDepositByOrderCode(ctx context.Context, orderCode string) (Deposit, error)
	GetLatestPendingWithdrawal(ctx context.Context, userID int64) (Withdrawal, error)
	GetWallet(ctx context.Context, arg GetWalletParams) (GetWalletRow, error)
	GetWithdrawalByID(ctx context.Context, id int64) (Withdrawal, error)
	// Add amount to locked unconditionally (the availability check already happened
	// on the Redis hot path).
	IncreaseLocked(ctx context.Context, arg IncreaseLockedParams) error
	// Idempotent insert used by provisioning; an existing (user,currency) is left
	// untouched.
	InsertWallet(ctx context.Context, arg InsertWalletParams) error
	ListAllWallets(ctx context.Context) ([]ListAllWalletsRow, error)
	// Admin read model: optional status filter and optional free-text search on the
	// owning user's email. An empty string disables the corresponding filter.
	ListDepositsAdmin(ctx context.Context, arg ListDepositsAdminParams) ([]Deposit, error)
	ListDepositsByUser(ctx context.Context, arg ListDepositsByUserParams) ([]Deposit, error)
	ListWalletsByUser(ctx context.Context, userID int64) ([]ListWalletsByUserRow, error)
	// Admin read model: optional status filter and optional free-text search on the
	// owning user's email OR the destination bank account.
	ListWithdrawalsAdmin(ctx context.Context, arg ListWithdrawalsAdminParams) ([]Withdrawal, error)
	ListWithdrawalsByUser(ctx context.Context, arg ListWithdrawalsByUserParams) ([]Withdrawal, error)
	// Move amount from available into locked; affects zero rows (caller treats as
	// insufficient) when available < amount.
	LockBalance(ctx context.Context, arg LockBalanceParams) (int64, error)
	// Release amount from locked, floored at zero.
	UnlockBalance(ctx context.Context, arg UnlockBalanceParams) error
	// Add a signed delta. The guard makes a debit (delta < 0) affect zero rows when
	// it would overdraw; a credit always passes since balance and delta are both
	// non-negative in that case.
	UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (int64, error)
	// Persist the mutable fields after a state transition (Confirm/Fail) or once the
	// bank reference is known.
	UpdateDeposit(ctx context.Context, arg UpdateDepositParams) error
	UpdateWithdrawal(ctx context.Context, arg UpdateWithdrawalParams) error
	// Credit balance, creating the wallet row if it does not yet exist.
	UpsertWalletCredit(ctx context.Context, arg UpsertWalletCreditParams) error
}

var _ Querier = (*Queries)(nil)
