// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets.sql

package sqlc

import (
	"context"
)

const countWalletsByUser = `-- name: CountWalletsByUser :one
SELECT count(*) FROM wallets WHERE user_id = $1
`

func (q *Queries) CountWalletsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countWalletsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWallet = `-- name: GetWallet :one
SELECT user_id, currency, balance, locked_balance
FROM wallets
WHERE user_id = $1 AND currency = $2
`

type GetWalletParams struct {
	UserID   int64  `json:"user_id"`
	Currency string `json:"currency"`
}

type GetWalletRow struct {
	UserID        int64   `json:"user_id"`
	Currency      string  `json:"currency"`
	Balance       float64 `json:"balance"`
	LockedBalance float64 `json:"locked_balance"`
}

func (q *Queries) GetWallet(ctx context.Context, arg GetWalletParams) (GetWalletRow, error) {
	row := q.db.QueryRow(ctx, getWallet, arg.UserID, arg.Currency)
	var i GetWalletRow
	err := row.Scan(
		&i.UserID,
		&i.Currency,
		&i.Balance,
		&i.LockedBalance,
	)
	return i, err
}

const increaseLocked = `-- name: IncreaseLocked :exec
UPDATE wallets
SET locked_balance = locked_balance + $1::numeric, updated_at = now()
WHERE user_id = $2 AND currency = $3
`

type IncreaseLockedParams struct {
	Amount   float64 `json:"amount"`
	UserID   int64   `json:"user_id"`
	Currency string  `json:"currency"`
}

// Add amount to locked unconditionally (the availability check already happened
// on the Redis hot path).
func (q *Queries) IncreaseLocked(ctx context.Context, arg IncreaseLockedParams) error {
	_, err := q.db.Exec(ctx, increaseLocked, arg.Amount, arg.UserID, arg.Currency)
	return err
}

const insertWallet = `-- name: InsertWallet :exec
INSERT INTO wallets (user_id, currency, balance, locked_balance)
VALUES ($1, $2, $3, 0)
ON CONFLICT (user_id, currency) DO NOTHING
`

type InsertWalletParams struct {
	UserID   int64   `json:"user_id"`
	Currency string  `json:"currency"`
	Balance  float64 `json:"balance"`
}

// Idempotent insert used by provisioning; an existing (user,currency) is left
// untouched.
func (q *Queries) InsertWallet(ctx context.Context, arg InsertWalletParams) error {
	_, err := q.db.Exec(ctx, insertWallet, arg.UserID, arg.Currency, arg.Balance)
	return err
}

const listAllWallets = `-- name: ListAllWallets :many
SELECT user_id, currency, balance, locked_balance
FROM wallets
`

type ListAllWalletsRow struct {
	UserID        int64   `json:"user_id"`
	Currency      string  `json:"currency"`
	Balance       float64 `json:"balance"`
	LockedBalance float64 `json:"locked_balance"`
}

func (q *Queries) ListAllWallets(ctx context.Context) ([]ListAllWalletsRow, error) {
	rows, err := q.db.Query(ctx, listAllWallets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllWalletsRow{}
	for rows.Next() {
		var i ListAllWalletsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Currency,
			&i.Balance,
			&i.LockedBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletsByUser = `-- name: ListWalletsByUser :many
SELECT user_id, currency, balance, locked_balance
FROM wallets
WHERE user_id = $1
ORDER BY currency
`

type ListWalletsByUserRow struct {
	UserID        int64   `json:"user_id"`
	Currency      string  `json:"currency"`
	Balance       float64 `json:"balance"`
	LockedBalance float64 `json:"locked_balance"`
}

func (q *Queries) ListWalletsByUser(ctx context.Context, userID int64) ([]ListWalletsByUserRow, error) {
	rows, err := q.db.Query(ctx, listWalletsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWalletsByUserRow{}
	for rows.Next() {
		var i ListWalletsByUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.Currency,
			&i.Balance,
			&i.LockedBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBalance = `-- name: LockBalance :execrows
UPDATE wallets
SET locked_balance = locked_balance + $1::numeric, updated_at = now()
WHERE user_id = $2 AND currency = $3
  AND (balance - locked_balance) >= $1::numeric
`

type LockBalanceParams struct {
	Amount   float64 `json:"amount"`
	UserID   int64   `json:"user_id"`
	Currency string  `json:"currency"`
}

// Move amount from available into locked; affects zero rows (caller treats as
// insufficient) when available < amount.
func (q *Queries) LockBalance(ctx context.Context, arg LockBalanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, lockBalance, arg.Amount, arg.UserID, arg.Currency)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unlockBalance = `-- name: UnlockBalance :exec
UPDATE wallets
SET locked_balance = CASE
        WHEN locked_balance - $1::numeric < 0 THEN 0
        ELSE locked_balance - $1::numeric
    END,
    updated_at = now()
WHERE user_id = $2 AND currency = $3
`

type UnlockBalanceParams struct {
	Amount   float64 `json:"amount"`
	UserID   int64   `json:"user_id"`
	Currency string  `json:"currency"`
}

// Release amount from locked, floored at zero.
func (q *Queries) UnlockBalance(ctx context.Context, arg UnlockBalanceParams) error {
	_, err := q.db.Exec(ctx, unlockBalance, arg.Amount, arg.UserID, arg.Currency)
	return err
}

const updateBalance = `-- name: UpdateBalance :execrows
UPDATE wallets
SET balance = balance + $1::numeric, updated_at = now()
WHERE user_id = $2 AND currency = $3 AND balance + $1::numeric >= 0
`

type UpdateBalanceParams struct {
	Delta    float64 `json:"delta"`
	UserID   int64   `json:"user_id"`
	Currency string  `json:"currency"`
}

// Add a signed delta. The guard makes a debit (delta < 0) affect zero rows when
// it would overdraw; a credit always passes since balance and delta are both
// non-negative in that case.
func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBalance, arg.Delta, arg.UserID, arg.Currency)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertWalletCredit = `-- name: UpsertWalletCredit :exec
INSERT INTO wallets (user_id, currency, balance, locked_balance, updated_at)
VALUES ($1, $2, $3::numeric, 0, now())
ON CONFLICT (user_id, currency)
DO UPDATE SET balance = wallets.balance + EXCLUDED.balance, updated_at = now()
`

type UpsertWalletCreditParams struct {
	UserID   int64   `json:"user_id"`
	Currency string  `json:"currency"`
	Amount   float64 `json:"amount"`
}

// Credit balance, creating the wallet row if it does not yet exist.
func (q *Queries) UpsertWalletCredit(ctx context.Context, arg UpsertWalletCreditParams) error {
	_, err := q.db.Exec(ctx, upsertWalletCredit, arg.UserID, arg.Currency, arg.Amount)
	return err
}
