// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: withdrawals.sql

package sqlc

import (
	"context"
)

const countWithdrawalsAdmin = `-- name: CountWithdrawalsAdmin :one
SELECT count(*)
FROM withdrawals w
WHERE ($1::text = '' OR w.status = $1::text)
  AND ($2::text = '' OR w.bank_account ILIKE '%' || $2::text || '%' OR EXISTS (
        SELECT 1 FROM users u WHERE u.id = w.user_id AND u.email ILIKE '%' || $2::text || '%'))
`

type CountWithdrawalsAdminParams struct {
	Status string `json:"status"`
	Search string `json:"search"`
}

func (q *Queries) CountWithdrawalsAdmin(ctx context.Context, arg CountWithdrawalsAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWithdrawalsAdmin, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWithdrawalsByUser = `-- name: CountWithdrawalsByUser :one
SELECT count(*) FROM withdrawals WHERE user_id = $1
`

func (q *Queries) CountWithdrawalsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countWithdrawalsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWithdrawal = `-- name: CreateWithdrawal :one
INSERT INTO withdrawals (user_id, amount, currency, bank_code, bank_account, account_name, status, admin_note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, amount, currency, bank_code, bank_account, account_name, status, admin_note, created_at, updated_at
`

type CreateWithdrawalParams struct {
	UserID      int64   `json:"user_id"`
	Amount      float64 `json:"amount"`
	Currency    string  `json:"currency"`
	BankCode    string  `json:"bank_code"`
	BankAccount string  `json:"bank_account"`
	AccountName string  `json:"account_name"`
	Status      string  `json:"status"`
	AdminNote   string  `json:"admin_note"`
}

func (q *Queries) CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) (Withdrawal, error) {
	row := q.db.QueryRow(ctx, createWithdrawal,
		arg.UserID,
		arg.Amount,
		arg.Currency,
		arg.BankCode,
		arg.BankAccount,
		arg.AccountName,
		arg.Status,
		arg.AdminNote,
	)
	var i Withdrawal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.BankCode,
		&i.BankAccount,
		&i.AccountName,
		&i.Status,
		&i.AdminNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestPendingWithdrawal = `-- name: GetLatestPendingWithdrawal :one
SELECT id, user_id, amount, currency, bank_code, bank_account, account_name, status, admin_note, created_at, updated_at
FROM withdrawals
WHERE user_id = $1 AND status = 'PENDING'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestPendingWithdrawal(ctx context.Context, userID int64) (Withdrawal, error) {
	row := q.db.QueryRow(ctx, getLatestPendingWithdrawal, userID)
	var i Withdrawal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.BankCode,
		&i.BankAccount,
		&i.AccountName,
		&i.Status,
		&i.AdminNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWithdrawalByID = `-- name: GetWithdrawalByID :one
SELECT id, user_id, amount, currency, bank_code, bank_account, account_name, status, admin_note, created_at, updated_at
FROM withdrawals
WHERE id = $1
`

func (q *Queries) GetWithdrawalByID(ctx context.Context, id int64) (Withdrawal, error) {
	row := q.db.QueryRow(ctx, getWithdrawalByID, id)
	var i Withdrawal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.BankCode,
		&i.BankAccount,
		&i.AccountName,
		&i.Status,
		&i.AdminNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWithdrawalsAdmin = `-- name: ListWithdrawalsAdmin :many
SELECT w.id, w.user_id, w.amount, w.currency, w.bank_code, w.bank_account, w.account_name, w.status, w.admin_note, w.created_at, w.updated_at
FROM withdrawals w
WHERE ($1::text = '' OR w.status = $1::text)
  AND ($2::text = '' OR w.bank_account ILIKE '%' || $2::text || '%' OR EXISTS (
        SELECT 1 FROM users u WHERE u.id = w.user_id AND u.email ILIKE '%' || $2::text || '%'))
ORDER BY w.created_at DESC
LIMIT $4 OFFSET $3
`

type ListWithdrawalsAdminParams struct {
	Status string `json:"status"`
	Search string `json:"search"`
	Off    int32  `json:"off"`
	Lim    int32  `json:"lim"`
}

// Admin read model: optional status filter and optional free-text search on the
// owning user's email OR the destination bank account.
func (q *Queries) ListWithdrawalsAdmin(ctx context.Context, arg ListWithdrawalsAdminParams) ([]Withdrawal, error) {
	rows, err := q.db.Query(ctx, listWithdrawalsAdmin,
		arg.Status,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Withdrawal{}
	for rows.Next() {
		var i Withdrawal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Currency,
			&i.BankCode,
			&i.BankAccount,
			&i.AccountName,
			&i.Status,
			&i.AdminNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawalsByUser = `-- name: ListWithdrawalsByUser :many
SELECT id, user_id, amount, currency, bank_code, bank_account, account_name, status, admin_note, created_at, updated_at
FROM withdrawals
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWithdrawalsByUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListWithdrawalsByUser(ctx context.Context, arg ListWithdrawalsByUserParams) ([]Withdrawal, error) {
	rows, err := q.db.Query(ctx, listWithdrawalsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Withdrawal{}
	for rows.Next() {
		var i Withdrawal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Currency,
			&i.BankCode,
			&i.BankAccount,
			&i.AccountName,
			&i.Status,
			&i.AdminNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWithdrawal = `-- name: UpdateWithdrawal :exec
UPDATE withdrawals
SET status = $2, admin_note = $3, updated_at = now()
WHERE id = $1
`

type UpdateWithdrawalParams struct {
	ID        int64  `json:"id"`
	Status    string `json:"status"`
	AdminNote string `json:"admin_note"`
}

func (q *Queries) UpdateWithdrawal(ctx context.Context, arg UpdateWithdrawalParams) error {
	_, err := q.db.Exec(ctx, updateWithdrawal, arg.ID, arg.Status, arg.AdminNote)
	return err
}
