// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candles.sql

package sqlc

import (
	"context"
	"time"
)

const queryCandles = `-- name: QueryCandles :many
SELECT pair, interval, open_time, open, high, low, close, volume
FROM (
    SELECT pair, interval, open_time, open, high, low, close, volume
    FROM candles
    WHERE pair = $1 AND interval = $2
    ORDER BY open_time DESC
    LIMIT $3
) sub
ORDER BY open_time ASC
`

type QueryCandlesParams struct {
	Pair     string `json:"pair"`
	Interval string `json:"interval"`
	Limit    int32  `json:"limit"`
}

type QueryCandlesRow struct {
	Pair     string    `json:"pair"`
	Interval string    `json:"interval"`
	OpenTime time.Time `json:"open_time"`
	Open     float64   `json:"open"`
	High     float64   `json:"high"`
	Low      float64   `json:"low"`
	Close    float64   `json:"close"`
	Volume   float64   `json:"volume"`
}

// The most-recent `limit` bars for (pair, interval), returned in ASCENDING
// open_time order (the inner query takes the newest rows, the outer re-sorts).
func (q *Queries) QueryCandles(ctx context.Context, arg QueryCandlesParams) ([]QueryCandlesRow, error) {
	rows, err := q.db.Query(ctx, queryCandles, arg.Pair, arg.Interval, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueryCandlesRow{}
	for rows.Next() {
		var i QueryCandlesRow
		if err := rows.Scan(
			&i.Pair,
			&i.Interval,
			&i.OpenTime,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCandle = `-- name: UpsertCandle :exec
INSERT INTO candles (pair, interval, open_time, open, high, low, close, volume)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (pair, interval, open_time)
DO UPDATE SET open = EXCLUDED.open, high = EXCLUDED.high, low = EXCLUDED.low,
              close = EXCLUDED.close, volume = EXCLUDED.volume
`

type UpsertCandleParams struct {
	Pair     string    `json:"pair"`
	Interval string    `json:"interval"`
	OpenTime time.Time `json:"open_time"`
	Open     float64   `json:"open"`
	High     float64   `json:"high"`
	Low      float64   `json:"low"`
	Close    float64   `json:"close"`
	Volume   float64   `json:"volume"`
}

// Write a completed candle, overwriting an existing bar with the same
// (pair, interval, open_time).
func (q *Queries) UpsertCandle(ctx context.Context, arg UpsertCandleParams) error {
	_, err := q.db.Exec(ctx, upsertCandle,
		arg.Pair,
		arg.Interval,
		arg.OpenTime,
		arg.Open,
		arg.High,
		arg.Low,
		arg.Close,
		arg.Volume,
	)
	return err
}
