// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	// The most-recent `limit` bars for (pair, interval), returned in ASCENDING
	// open_time order (the inner query takes the newest rows, the outer re-sorts).
	QueryCandles(ctx context.Context, arg QueryCandlesParams) ([]QueryCandlesRow, error)
	// Write a completed candle, overwriting an existing bar with the same
	// (pair, interval, open_time).
	UpsertCandle(ctx context.Context, arg UpsertCandleParams) error
}

var _ Querier = (*Queries)(nil)
