// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"
)

const countByUser = `-- name: CountByUser :one
SELECT count(*) FROM notifications WHERE user_id = $1
`

func (q *Queries) CountByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadByUser = `-- name: CountUnreadByUser :one
SELECT count(*) FROM notifications WHERE user_id = $1 AND is_read = false
`

func (q *Queries) CountUnreadByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, title, message, pair, is_read)
VALUES ($1, $2, $3, $4, $5, false)
RETURNING id, user_id, type, title, message, pair, is_read, created_at
`

type CreateNotificationParams struct {
	UserID  int64  `json:"user_id"`
	Type    string `json:"type"`
	Title   string `json:"title"`
	Message string `json:"message"`
	Pair    string `json:"pair"`
}

// Insert a notification, returning the persisted row. All values parameterized.
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Message,
		arg.Pair,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.Pair,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const listByUser = `-- name: ListByUser :many
SELECT id, user_id, type, title, message, pair, is_read, created_at
FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListByUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Page of a user's notifications, newest first.
func (q *Queries) ListByUser(ctx context.Context, arg ListByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.Pair,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadByUser = `-- name: ListUnreadByUser :many
SELECT id, user_id, type, title, message, pair, is_read, created_at
FROM notifications
WHERE user_id = $1 AND is_read = false
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListUnreadByUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Page of a user's UNREAD notifications, newest first.
func (q *Queries) ListUnreadByUser(ctx context.Context, arg ListUnreadByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUnreadByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.Pair,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllRead = `-- name: MarkAllRead :exec
UPDATE notifications SET is_read = true WHERE user_id = $1 AND is_read = false
`

func (q *Queries) MarkAllRead(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, markAllRead, userID)
	return err
}

const markAsRead = `-- name: MarkAsRead :exec
UPDATE notifications SET is_read = true WHERE id = $1 AND user_id = $2
`

type MarkAsReadParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

// Mark one notification read, scoped to its owner (an attacker cannot flip
// another user's row).
func (q *Queries) MarkAsRead(ctx context.Context, arg MarkAsReadParams) error {
	_, err := q.db.Exec(ctx, markAsRead, arg.ID, arg.UserID)
	return err
}
