// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CountByUser(ctx context.Context, userID int64) (int64, error)
	CountUnreadByUser(ctx context.Context, userID int64) (int64, error)
	// Insert a notification, returning the persisted row. All values parameterized.
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	// Page of a user's notifications, newest first.
	ListByUser(ctx context.Context, arg ListByUserParams) ([]Notification, error)
	// Page of a user's UNREAD notifications, newest first.
	ListUnreadByUser(ctx context.Context, arg ListUnreadByUserParams) ([]Notification, error)
	MarkAllRead(ctx context.Context, userID int64) error
	// Mark one notification read, scoped to its owner (an attacker cannot flip
	// another user's row).
	MarkAsRead(ctx context.Context, arg MarkAsReadParams) error
}

var _ Querier = (*Queries)(nil)
