// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sqlc

import (
	"context"
	"time"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, label, key_id, secret_hash, permissions, ip_whitelist, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at
`

type CreateAPIKeyParams struct {
	UserID      int64      `json:"user_id"`
	Label       string     `json:"label"`
	KeyID       string     `json:"key_id"`
	SecretHash  string     `json:"secret_hash"`
	Permissions string     `json:"permissions"`
	IpWhitelist string     `json:"ip_whitelist"`
	ExpiresAt   *time.Time `json:"expires_at"`
}

type CreateAPIKeyRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.Label,
		arg.KeyID,
		arg.SecretHash,
		arg.Permissions,
		arg.IpWhitelist,
		arg.ExpiresAt,
	)
	var i CreateAPIKeyRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getAPIKeyByKeyID = `-- name: GetAPIKeyByKeyID :one
SELECT id, user_id, label, key_id, secret_hash, permissions, ip_whitelist, last_used_at, last_used_ip, expires_at, revoked_at, created_at
FROM api_keys WHERE key_id = $1 AND revoked_at IS NULL
`

func (q *Queries) GetAPIKeyByKeyID(ctx context.Context, keyID string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByKeyID, keyID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.KeyID,
		&i.SecretHash,
		&i.Permissions,
		&i.IpWhitelist,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, user_id, label, key_id, secret_hash, permissions, ip_whitelist, last_used_at, last_used_ip, expires_at, revoked_at, created_at
FROM api_keys WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID int64) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.KeyID,
			&i.SecretHash,
			&i.Permissions,
			&i.IpWhitelist,
			&i.LastUsedAt,
			&i.LastUsedIp,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET revoked_at = now() WHERE id = $1 AND user_id = $2
`

type RevokeAPIKeyParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.UserID)
	return err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = now(), last_used_ip = $2 WHERE id = $1
`

type UpdateAPIKeyLastUsedParams struct {
	ID         int64  `json:"id"`
	LastUsedIp string `json:"last_used_ip"`
}

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, arg.ID, arg.LastUsedIp)
	return err
}
