// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package sqlc

import (
	"context"
	"time"
)

const countAuditAll = `-- name: CountAuditAll :one
SELECT count(*) FROM audit_logs WHERE ($1::text = '' OR action = $1::text)
`

func (q *Queries) CountAuditAll(ctx context.Context, action string) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditAll, action)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditByUser = `-- name: CountAuditByUser :one
SELECT count(*) FROM audit_logs WHERE user_id = $1
`

func (q *Queries) CountAuditByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditDeviceForUser = `-- name: CountAuditDeviceForUser :one
SELECT count(*) FROM audit_logs WHERE user_id = $1 AND device_id = $2
`

type CountAuditDeviceForUserParams struct {
	UserID   int64  `json:"user_id"`
	DeviceID string `json:"device_id"`
}

func (q *Queries) CountAuditDeviceForUser(ctx context.Context, arg CountAuditDeviceForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditDeviceForUser, arg.UserID, arg.DeviceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (user_id, email, action, outcome, ip, user_agent, device_id, new_device, detail)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, created_at
`

type CreateAuditLogParams struct {
	UserID    int64  `json:"user_id"`
	Email     string `json:"email"`
	Action    string `json:"action"`
	Outcome   string `json:"outcome"`
	Ip        string `json:"ip"`
	UserAgent string `json:"user_agent"`
	DeviceID  string `json:"device_id"`
	NewDevice bool   `json:"new_device"`
	Detail    string `json:"detail"`
}

type CreateAuditLogRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (CreateAuditLogRow, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.UserID,
		arg.Email,
		arg.Action,
		arg.Outcome,
		arg.Ip,
		arg.UserAgent,
		arg.DeviceID,
		arg.NewDevice,
		arg.Detail,
	)
	var i CreateAuditLogRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listAuditAll = `-- name: ListAuditAll :many
SELECT id, user_id, email, action, outcome, ip, user_agent, device_id, new_device, detail, created_at
FROM audit_logs
WHERE ($1::text = '' OR action = $1::text)
ORDER BY created_at DESC LIMIT $3 OFFSET $2
`

type ListAuditAllParams struct {
	Action string `json:"action"`
	Off    int32  `json:"off"`
	Lim    int32  `json:"lim"`
}

// An empty @action disables the action filter.
func (q *Queries) ListAuditAll(ctx context.Context, arg ListAuditAllParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditAll, arg.Action, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.Action,
			&i.Outcome,
			&i.Ip,
			&i.UserAgent,
			&i.DeviceID,
			&i.NewDevice,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditByUser = `-- name: ListAuditByUser :many
SELECT id, user_id, email, action, outcome, ip, user_agent, device_id, new_device, detail, created_at
FROM audit_logs WHERE user_id = $1
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListAuditByUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditByUser(ctx context.Context, arg ListAuditByUserParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.Action,
			&i.Outcome,
			&i.Ip,
			&i.UserAgent,
			&i.DeviceID,
			&i.NewDevice,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAuditOlderThan = `-- name: PruneAuditOlderThan :execrows
DELETE FROM audit_logs WHERE created_at < $1
`

func (q *Queries) PruneAuditOlderThan(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneAuditOlderThan, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
