// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bonus.sql

package sqlc

import (
	"context"
	"time"
)

const createPromotion = `-- name: CreatePromotion :one
INSERT INTO bonus_promotions (name, description, bonus_percent, max_bonus_amount, target_type, target_user_ids, trigger_type, min_deposit, is_active, start_at, end_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, created_at
`

type CreatePromotionParams struct {
	Name           string    `json:"name"`
	Description    string    `json:"description"`
	BonusPercent   float64   `json:"bonus_percent"`
	MaxBonusAmount float64   `json:"max_bonus_amount"`
	TargetType     string    `json:"target_type"`
	TargetUserIds  string    `json:"target_user_ids"`
	TriggerType    string    `json:"trigger_type"`
	MinDeposit     float64   `json:"min_deposit"`
	IsActive       bool      `json:"is_active"`
	StartAt        time.Time `json:"start_at"`
	EndAt          time.Time `json:"end_at"`
}

type CreatePromotionRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreatePromotion(ctx context.Context, arg CreatePromotionParams) (CreatePromotionRow, error) {
	row := q.db.QueryRow(ctx, createPromotion,
		arg.Name,
		arg.Description,
		arg.BonusPercent,
		arg.MaxBonusAmount,
		arg.TargetType,
		arg.TargetUserIds,
		arg.TriggerType,
		arg.MinDeposit,
		arg.IsActive,
		arg.StartAt,
		arg.EndAt,
	)
	var i CreatePromotionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createUserBonus = `-- name: CreateUserBonus :one
INSERT INTO user_bonus (user_id, promotion_id, deposit_id, bonus_amount, used_amount, status, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at
`

type CreateUserBonusParams struct {
	UserID      int64      `json:"user_id"`
	PromotionID int64      `json:"promotion_id"`
	DepositID   int64      `json:"deposit_id"`
	BonusAmount float64    `json:"bonus_amount"`
	UsedAmount  float64    `json:"used_amount"`
	Status      string     `json:"status"`
	ExpiresAt   *time.Time `json:"expires_at"`
}

type CreateUserBonusRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateUserBonus(ctx context.Context, arg CreateUserBonusParams) (CreateUserBonusRow, error) {
	row := q.db.QueryRow(ctx, createUserBonus,
		arg.UserID,
		arg.PromotionID,
		arg.DepositID,
		arg.BonusAmount,
		arg.UsedAmount,
		arg.Status,
		arg.ExpiresAt,
	)
	var i CreateUserBonusRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const findActivePromotions = `-- name: FindActivePromotions :many
SELECT id, name, description, bonus_percent, max_bonus_amount, target_type, target_user_ids, trigger_type, min_deposit, is_active, start_at, end_at, created_at
FROM bonus_promotions WHERE is_active = true
`

func (q *Queries) FindActivePromotions(ctx context.Context) ([]BonusPromotion, error) {
	rows, err := q.db.Query(ctx, findActivePromotions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BonusPromotion{}
	for rows.Next() {
		var i BonusPromotion
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.BonusPercent,
			&i.MaxBonusAmount,
			&i.TargetType,
			&i.TargetUserIds,
			&i.TriggerType,
			&i.MinDeposit,
			&i.IsActive,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findActiveUserBonuses = `-- name: FindActiveUserBonuses :many
SELECT id, user_id, promotion_id, deposit_id, bonus_amount, used_amount, status, created_at, expires_at
FROM user_bonus WHERE user_id = $1 AND status = 'ACTIVE' ORDER BY created_at ASC
`

func (q *Queries) FindActiveUserBonuses(ctx context.Context, userID int64) ([]UserBonu, error) {
	rows, err := q.db.Query(ctx, findActiveUserBonuses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserBonu{}
	for rows.Next() {
		var i UserBonu
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PromotionID,
			&i.DepositID,
			&i.BonusAmount,
			&i.UsedAmount,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllPromotions = `-- name: FindAllPromotions :many
SELECT id, name, description, bonus_percent, max_bonus_amount, target_type, target_user_ids, trigger_type, min_deposit, is_active, start_at, end_at, created_at
FROM bonus_promotions ORDER BY created_at DESC
`

func (q *Queries) FindAllPromotions(ctx context.Context) ([]BonusPromotion, error) {
	rows, err := q.db.Query(ctx, findAllPromotions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BonusPromotion{}
	for rows.Next() {
		var i BonusPromotion
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.BonusPercent,
			&i.MaxBonusAmount,
			&i.TargetType,
			&i.TargetUserIds,
			&i.TriggerType,
			&i.MinDeposit,
			&i.IsActive,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPromotionByID = `-- name: FindPromotionByID :one
SELECT id, name, description, bonus_percent, max_bonus_amount, target_type, target_user_ids, trigger_type, min_deposit, is_active, start_at, end_at, created_at
FROM bonus_promotions WHERE id = $1
`

func (q *Queries) FindPromotionByID(ctx context.Context, id int64) (BonusPromotion, error) {
	row := q.db.QueryRow(ctx, findPromotionByID, id)
	var i BonusPromotion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BonusPercent,
		&i.MaxBonusAmount,
		&i.TargetType,
		&i.TargetUserIds,
		&i.TriggerType,
		&i.MinDeposit,
		&i.IsActive,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
	)
	return i, err
}

const findUserBonuses = `-- name: FindUserBonuses :many
SELECT id, user_id, promotion_id, deposit_id, bonus_amount, used_amount, status, created_at, expires_at
FROM user_bonus WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) FindUserBonuses(ctx context.Context, userID int64) ([]UserBonu, error) {
	rows, err := q.db.Query(ctx, findUserBonuses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserBonu{}
	for rows.Next() {
		var i UserBonu
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PromotionID,
			&i.DepositID,
			&i.BonusAmount,
			&i.UsedAmount,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumActiveBonus = `-- name: SumActiveBonus :one
SELECT COALESCE(SUM(bonus_amount - used_amount), 0)::numeric
FROM user_bonus WHERE user_id = $1 AND status = 'ACTIVE'
`

func (q *Queries) SumActiveBonus(ctx context.Context, userID int64) (float64, error) {
	row := q.db.QueryRow(ctx, sumActiveBonus, userID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const updatePromotion = `-- name: UpdatePromotion :exec
UPDATE bonus_promotions SET
    name = $2, description = $3, bonus_percent = $4, max_bonus_amount = $5, target_type = $6,
    target_user_ids = $7, trigger_type = $8, min_deposit = $9, is_active = $10, start_at = $11, end_at = $12
WHERE id = $1
`

type UpdatePromotionParams struct {
	ID             int64     `json:"id"`
	Name           string    `json:"name"`
	Description    string    `json:"description"`
	BonusPercent   float64   `json:"bonus_percent"`
	MaxBonusAmount float64   `json:"max_bonus_amount"`
	TargetType     string    `json:"target_type"`
	TargetUserIds  string    `json:"target_user_ids"`
	TriggerType    string    `json:"trigger_type"`
	MinDeposit     float64   `json:"min_deposit"`
	IsActive       bool      `json:"is_active"`
	StartAt        time.Time `json:"start_at"`
	EndAt          time.Time `json:"end_at"`
}

func (q *Queries) UpdatePromotion(ctx context.Context, arg UpdatePromotionParams) error {
	_, err := q.db.Exec(ctx, updatePromotion,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.BonusPercent,
		arg.MaxBonusAmount,
		arg.TargetType,
		arg.TargetUserIds,
		arg.TriggerType,
		arg.MinDeposit,
		arg.IsActive,
		arg.StartAt,
		arg.EndAt,
	)
	return err
}

const updateUserBonus = `-- name: UpdateUserBonus :exec
UPDATE user_bonus SET
    user_id = $2, promotion_id = $3, deposit_id = $4, bonus_amount = $5, used_amount = $6, status = $7, expires_at = $8
WHERE id = $1
`

type UpdateUserBonusParams struct {
	ID          int64      `json:"id"`
	UserID      int64      `json:"user_id"`
	PromotionID int64      `json:"promotion_id"`
	DepositID   int64      `json:"deposit_id"`
	BonusAmount float64    `json:"bonus_amount"`
	UsedAmount  float64    `json:"used_amount"`
	Status      string     `json:"status"`
	ExpiresAt   *time.Time `json:"expires_at"`
}

func (q *Queries) UpdateUserBonus(ctx context.Context, arg UpdateUserBonusParams) error {
	_, err := q.db.Exec(ctx, updateUserBonus,
		arg.ID,
		arg.UserID,
		arg.PromotionID,
		arg.DepositID,
		arg.BonusAmount,
		arg.UsedAmount,
		arg.Status,
		arg.ExpiresAt,
	)
	return err
}
