// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fee_tiers.sql

package sqlc

import (
	"context"
)

const countFeeTiers = `-- name: CountFeeTiers :one
SELECT count(*) FROM fee_tiers
`

func (q *Queries) CountFeeTiers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFeeTiers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFeeTierByLevel = `-- name: GetFeeTierByLevel :one
SELECT id, level, name, min_volume, maker_fee, taker_fee, description
FROM fee_tiers WHERE level = $1
`

func (q *Queries) GetFeeTierByLevel(ctx context.Context, level int32) (FeeTier, error) {
	row := q.db.QueryRow(ctx, getFeeTierByLevel, level)
	var i FeeTier
	err := row.Scan(
		&i.ID,
		&i.Level,
		&i.Name,
		&i.MinVolume,
		&i.MakerFee,
		&i.TakerFee,
		&i.Description,
	)
	return i, err
}

const getUserVolume = `-- name: GetUserVolume :one
SELECT user_id, volume, tier_level, updated_at FROM user_volume30ds WHERE user_id = $1
`

func (q *Queries) GetUserVolume(ctx context.Context, userID int64) (UserVolume30d, error) {
	row := q.db.QueryRow(ctx, getUserVolume, userID)
	var i UserVolume30d
	err := row.Scan(
		&i.UserID,
		&i.Volume,
		&i.TierLevel,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementVolume = `-- name: IncrementVolume :exec
INSERT INTO user_volume30ds (user_id, volume, tier_level, updated_at)
VALUES ($1, $2::numeric, 0, now())
ON CONFLICT (user_id) DO UPDATE SET volume = user_volume30ds.volume + EXCLUDED.volume, updated_at = now()
`

type IncrementVolumeParams struct {
	UserID int64   `json:"user_id"`
	Delta  float64 `json:"delta"`
}

func (q *Queries) IncrementVolume(ctx context.Context, arg IncrementVolumeParams) error {
	_, err := q.db.Exec(ctx, incrementVolume, arg.UserID, arg.Delta)
	return err
}

const insertFeeTier = `-- name: InsertFeeTier :exec
INSERT INTO fee_tiers (level, name, min_volume, maker_fee, taker_fee, description)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertFeeTierParams struct {
	Level       int32   `json:"level"`
	Name        string  `json:"name"`
	MinVolume   float64 `json:"min_volume"`
	MakerFee    float64 `json:"maker_fee"`
	TakerFee    float64 `json:"taker_fee"`
	Description string  `json:"description"`
}

func (q *Queries) InsertFeeTier(ctx context.Context, arg InsertFeeTierParams) error {
	_, err := q.db.Exec(ctx, insertFeeTier,
		arg.Level,
		arg.Name,
		arg.MinVolume,
		arg.MakerFee,
		arg.TakerFee,
		arg.Description,
	)
	return err
}

const listFeeTiers = `-- name: ListFeeTiers :many
SELECT id, level, name, min_volume, maker_fee, taker_fee, description
FROM fee_tiers ORDER BY level ASC
`

func (q *Queries) ListFeeTiers(ctx context.Context) ([]FeeTier, error) {
	rows, err := q.db.Query(ctx, listFeeTiers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeeTier{}
	for rows.Next() {
		var i FeeTier
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.Name,
			&i.MinVolume,
			&i.MakerFee,
			&i.TakerFee,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVolume = `-- name: UpsertVolume :exec
INSERT INTO user_volume30ds (user_id, volume, tier_level, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (user_id) DO UPDATE SET volume = EXCLUDED.volume, tier_level = EXCLUDED.tier_level, updated_at = now()
`

type UpsertVolumeParams struct {
	UserID    int64   `json:"user_id"`
	Volume    float64 `json:"volume"`
	TierLevel int32   `json:"tier_level"`
}

func (q *Queries) UpsertVolume(ctx context.Context, arg UpsertVolumeParams) error {
	_, err := q.db.Exec(ctx, upsertVolume, arg.UserID, arg.Volume, arg.TierLevel)
	return err
}
