// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fraud.sql

package sqlc

import (
	"context"
	"time"
)

const countFraudByTypeUsers = `-- name: CountFraudByTypeUsers :one
SELECT count(*) FROM fraud_logs WHERE fraud_type = $1 AND user_ids = $2
`

type CountFraudByTypeUsersParams struct {
	FraudType string `json:"fraud_type"`
	UserIds   string `json:"user_ids"`
}

func (q *Queries) CountFraudByTypeUsers(ctx context.Context, arg CountFraudByTypeUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFraudByTypeUsers, arg.FraudType, arg.UserIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFraudByTypeUsersActive = `-- name: CountFraudByTypeUsersActive :one
SELECT count(*) FROM fraud_logs
WHERE fraud_type = $1 AND user_ids = $2 AND action <> 'DISMISSED'
`

type CountFraudByTypeUsersActiveParams struct {
	FraudType string `json:"fraud_type"`
	UserIds   string `json:"user_ids"`
}

// Existing-flag guard for flagBonusFarming (ignores already-dismissed flags).
func (q *Queries) CountFraudByTypeUsersActive(ctx context.Context, arg CountFraudByTypeUsersActiveParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFraudByTypeUsersActive, arg.FraudType, arg.UserIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFraudLogs = `-- name: CountFraudLogs :one
SELECT count(*) FROM fraud_logs
WHERE ($1::text = '' OR user_ids ILIKE '%' || $1::text || '%'
       OR fraud_type ILIKE '%' || $1::text || '%'
       OR description ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountFraudLogs(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countFraudLogs, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFraudLog = `-- name: CreateFraudLog :one
INSERT INTO fraud_logs (user_ids, fraud_type, description, evidence, action, admin_note)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at
`

type CreateFraudLogParams struct {
	UserIds     string `json:"user_ids"`
	FraudType   string `json:"fraud_type"`
	Description string `json:"description"`
	Evidence    string `json:"evidence"`
	Action      string `json:"action"`
	AdminNote   string `json:"admin_note"`
}

type CreateFraudLogRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateFraudLog(ctx context.Context, arg CreateFraudLogParams) (CreateFraudLogRow, error) {
	row := q.db.QueryRow(ctx, createFraudLog,
		arg.UserIds,
		arg.FraudType,
		arg.Description,
		arg.Evidence,
		arg.Action,
		arg.AdminNote,
	)
	var i CreateFraudLogRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listFraudLogs = `-- name: ListFraudLogs :many
SELECT id, user_ids, fraud_type, description, evidence, action, admin_note, created_at
FROM fraud_logs
WHERE ($1::text = '' OR user_ids ILIKE '%' || $1::text || '%'
       OR fraud_type ILIKE '%' || $1::text || '%'
       OR description ILIKE '%' || $1::text || '%')
ORDER BY created_at DESC LIMIT $3 OFFSET $2
`

type ListFraudLogsParams struct {
	Search string `json:"search"`
	Off    int32  `json:"off"`
	Lim    int32  `json:"lim"`
}

// An empty @search disables the free-text filter.
func (q *Queries) ListFraudLogs(ctx context.Context, arg ListFraudLogsParams) ([]FraudLog, error) {
	rows, err := q.db.Query(ctx, listFraudLogs, arg.Search, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FraudLog{}
	for rows.Next() {
		var i FraudLog
		if err := rows.Scan(
			&i.ID,
			&i.UserIds,
			&i.FraudType,
			&i.Description,
			&i.Evidence,
			&i.Action,
			&i.AdminNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFraudAction = `-- name: UpdateFraudAction :exec
UPDATE fraud_logs SET action = $2, admin_note = $3 WHERE id = $1
`

type UpdateFraudActionParams struct {
	ID        int64  `json:"id"`
	Action    string `json:"action"`
	AdminNote string `json:"admin_note"`
}

func (q *Queries) UpdateFraudAction(ctx context.Context, arg UpdateFraudActionParams) error {
	_, err := q.db.Exec(ctx, updateFraudAction, arg.ID, arg.Action, arg.AdminNote)
	return err
}

const upsertUserTradePair = `-- name: UpsertUserTradePair :one
INSERT INTO user_trade_pairs (user1_id, user2_id, pair, trade_count, total_vol, first_trade, last_trade)
VALUES ($1, $2, $3, 1, $4::numeric, now(), now())
ON CONFLICT (user1_id, user2_id, pair)
DO UPDATE SET trade_count = user_trade_pairs.trade_count + 1,
              total_vol = user_trade_pairs.total_vol + EXCLUDED.total_vol,
              last_trade = now()
RETURNING trade_count, total_vol, first_trade
`

type UpsertUserTradePairParams struct {
	User1ID int64   `json:"user1_id"`
	User2ID int64   `json:"user2_id"`
	Pair    string  `json:"pair"`
	Total   float64 `json:"total"`
}

type UpsertUserTradePairRow struct {
	TradeCount int32     `json:"trade_count"`
	TotalVol   float64   `json:"total_vol"`
	FirstTrade time.Time `json:"first_trade"`
}

// Increment the cross-user trade counter for (user1<user2, pair); the conflict
// path bumps trade_count and adds the volume. Returns the post-update counters
// the fraud detector thresholds against.
func (q *Queries) UpsertUserTradePair(ctx context.Context, arg UpsertUserTradePairParams) (UpsertUserTradePairRow, error) {
	row := q.db.QueryRow(ctx, upsertUserTradePair,
		arg.User1ID,
		arg.User2ID,
		arg.Pair,
		arg.Total,
	)
	var i UpsertUserTradePairRow
	err := row.Scan(&i.TradeCount, &i.TotalVol, &i.FirstTrade)
	return i, err
}
