// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kyc.sql

package sqlc

import (
	"context"
	"time"
)

const createKYCDocument = `-- name: CreateKYCDocument :one
INSERT INTO kyc_documents (user_id, doc_type, file_path, status, admin_note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at
`

type CreateKYCDocumentParams struct {
	UserID    int64  `json:"user_id"`
	DocType   string `json:"doc_type"`
	FilePath  string `json:"file_path"`
	Status    string `json:"status"`
	AdminNote string `json:"admin_note"`
}

type CreateKYCDocumentRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateKYCDocument(ctx context.Context, arg CreateKYCDocumentParams) (CreateKYCDocumentRow, error) {
	row := q.db.QueryRow(ctx, createKYCDocument,
		arg.UserID,
		arg.DocType,
		arg.FilePath,
		arg.Status,
		arg.AdminNote,
	)
	var i CreateKYCDocumentRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createKYCProfile = `-- name: CreateKYCProfile :one
INSERT INTO kyc_profiles (user_id, first_name, last_name, date_of_birth, phone, address, ward, district, city, postal_code, country, occupation, income, trading_exp, purpose)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, created_at, updated_at
`

type CreateKYCProfileParams struct {
	UserID      int64  `json:"user_id"`
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	DateOfBirth string `json:"date_of_birth"`
	Phone       string `json:"phone"`
	Address     string `json:"address"`
	Ward        string `json:"ward"`
	District    string `json:"district"`
	City        string `json:"city"`
	PostalCode  string `json:"postal_code"`
	Country     string `json:"country"`
	Occupation  string `json:"occupation"`
	Income      string `json:"income"`
	TradingExp  string `json:"trading_exp"`
	Purpose     string `json:"purpose"`
}

type CreateKYCProfileRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateKYCProfile(ctx context.Context, arg CreateKYCProfileParams) (CreateKYCProfileRow, error) {
	row := q.db.QueryRow(ctx, createKYCProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.DateOfBirth,
		arg.Phone,
		arg.Address,
		arg.Ward,
		arg.District,
		arg.City,
		arg.PostalCode,
		arg.Country,
		arg.Occupation,
		arg.Income,
		arg.TradingExp,
		arg.Purpose,
	)
	var i CreateKYCProfileRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getKYCDocumentByUserAndType = `-- name: GetKYCDocumentByUserAndType :one
SELECT id, user_id, doc_type, file_path, status, admin_note, created_at
FROM kyc_documents WHERE user_id = $1 AND doc_type = $2
`

type GetKYCDocumentByUserAndTypeParams struct {
	UserID  int64  `json:"user_id"`
	DocType string `json:"doc_type"`
}

func (q *Queries) GetKYCDocumentByUserAndType(ctx context.Context, arg GetKYCDocumentByUserAndTypeParams) (KycDocument, error) {
	row := q.db.QueryRow(ctx, getKYCDocumentByUserAndType, arg.UserID, arg.DocType)
	var i KycDocument
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DocType,
		&i.FilePath,
		&i.Status,
		&i.AdminNote,
		&i.CreatedAt,
	)
	return i, err
}

const getKYCProfileByUser = `-- name: GetKYCProfileByUser :one
SELECT id, user_id, first_name, last_name, date_of_birth, phone, address, ward, district, city, postal_code, country, occupation, income, trading_exp, purpose, created_at, updated_at
FROM kyc_profiles WHERE user_id = $1
`

func (q *Queries) GetKYCProfileByUser(ctx context.Context, userID int64) (KycProfile, error) {
	row := q.db.QueryRow(ctx, getKYCProfileByUser, userID)
	var i KycProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Phone,
		&i.Address,
		&i.Ward,
		&i.District,
		&i.City,
		&i.PostalCode,
		&i.Country,
		&i.Occupation,
		&i.Income,
		&i.TradingExp,
		&i.Purpose,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listKYCDocumentsByUser = `-- name: ListKYCDocumentsByUser :many
SELECT id, user_id, doc_type, file_path, status, admin_note, created_at
FROM kyc_documents WHERE user_id = $1
`

func (q *Queries) ListKYCDocumentsByUser(ctx context.Context, userID int64) ([]KycDocument, error) {
	rows, err := q.db.Query(ctx, listKYCDocumentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KycDocument{}
	for rows.Next() {
		var i KycDocument
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DocType,
			&i.FilePath,
			&i.Status,
			&i.AdminNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAllKYCDocumentsStatus = `-- name: UpdateAllKYCDocumentsStatus :exec
UPDATE kyc_documents SET status = $2, admin_note = $3 WHERE user_id = $1
`

type UpdateAllKYCDocumentsStatusParams struct {
	UserID    int64  `json:"user_id"`
	Status    string `json:"status"`
	AdminNote string `json:"admin_note"`
}

func (q *Queries) UpdateAllKYCDocumentsStatus(ctx context.Context, arg UpdateAllKYCDocumentsStatusParams) error {
	_, err := q.db.Exec(ctx, updateAllKYCDocumentsStatus, arg.UserID, arg.Status, arg.AdminNote)
	return err
}

const updateKYCDocumentStatus = `-- name: UpdateKYCDocumentStatus :exec
UPDATE kyc_documents SET status = $2, admin_note = $3 WHERE id = $1
`

type UpdateKYCDocumentStatusParams struct {
	ID        int64  `json:"id"`
	Status    string `json:"status"`
	AdminNote string `json:"admin_note"`
}

func (q *Queries) UpdateKYCDocumentStatus(ctx context.Context, arg UpdateKYCDocumentStatusParams) error {
	_, err := q.db.Exec(ctx, updateKYCDocumentStatus, arg.ID, arg.Status, arg.AdminNote)
	return err
}

const updateKYCProfile = `-- name: UpdateKYCProfile :exec
UPDATE kyc_profiles SET
    first_name = $2, last_name = $3, date_of_birth = $4, phone = $5, address = $6, ward = $7,
    district = $8, city = $9, postal_code = $10, country = $11, occupation = $12, income = $13,
    trading_exp = $14, purpose = $15, updated_at = now()
WHERE id = $1
`

type UpdateKYCProfileParams struct {
	ID          int64  `json:"id"`
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	DateOfBirth string `json:"date_of_birth"`
	Phone       string `json:"phone"`
	Address     string `json:"address"`
	Ward        string `json:"ward"`
	District    string `json:"district"`
	City        string `json:"city"`
	PostalCode  string `json:"postal_code"`
	Country     string `json:"country"`
	Occupation  string `json:"occupation"`
	Income      string `json:"income"`
	TradingExp  string `json:"trading_exp"`
	Purpose     string `json:"purpose"`
}

func (q *Queries) UpdateKYCProfile(ctx context.Context, arg UpdateKYCProfileParams) error {
	_, err := q.db.Exec(ctx, updateKYCProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.DateOfBirth,
		arg.Phone,
		arg.Address,
		arg.Ward,
		arg.District,
		arg.City,
		arg.PostalCode,
		arg.Country,
		arg.Occupation,
		arg.Income,
		arg.TradingExp,
		arg.Purpose,
	)
	return err
}
