// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type ApiKey struct {
	ID          int64      `json:"id"`
	UserID      int64      `json:"user_id"`
	Label       string     `json:"label"`
	KeyID       string     `json:"key_id"`
	SecretHash  string     `json:"secret_hash"`
	Permissions string     `json:"permissions"`
	IpWhitelist string     `json:"ip_whitelist"`
	LastUsedAt  *time.Time `json:"last_used_at"`
	LastUsedIp  string     `json:"last_used_ip"`
	ExpiresAt   *time.Time `json:"expires_at"`
	RevokedAt   *time.Time `json:"revoked_at"`
	CreatedAt   time.Time  `json:"created_at"`
}

type AuditLog struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Email     string    `json:"email"`
	Action    string    `json:"action"`
	Outcome   string    `json:"outcome"`
	Ip        string    `json:"ip"`
	UserAgent string    `json:"user_agent"`
	DeviceID  string    `json:"device_id"`
	NewDevice bool      `json:"new_device"`
	Detail    string    `json:"detail"`
	CreatedAt time.Time `json:"created_at"`
}

type BonusPromotion struct {
	ID             int64     `json:"id"`
	Name           string    `json:"name"`
	Description    string    `json:"description"`
	BonusPercent   float64   `json:"bonus_percent"`
	MaxBonusAmount float64   `json:"max_bonus_amount"`
	TargetType     string    `json:"target_type"`
	TargetUserIds  string    `json:"target_user_ids"`
	TriggerType    string    `json:"trigger_type"`
	MinDeposit     float64   `json:"min_deposit"`
	IsActive       bool      `json:"is_active"`
	StartAt        time.Time `json:"start_at"`
	EndAt          time.Time `json:"end_at"`
	CreatedAt      time.Time `json:"created_at"`
}

type Coin struct {
	ID          int64  `json:"id"`
	Symbol      string `json:"symbol"`
	Name        string `json:"name"`
	CoinGeckoID string `json:"coin_gecko_id"`
	BybitSymbol string `json:"bybit_symbol"`
	IconUrl     string `json:"icon_url"`
	IsActive    bool   `json:"is_active"`
	SortOrder   int32  `json:"sort_order"`
	AssetType   string `json:"asset_type"`
}

type FeeTier struct {
	ID          int64   `json:"id"`
	Level       int32   `json:"level"`
	Name        string  `json:"name"`
	MinVolume   float64 `json:"min_volume"`
	MakerFee    float64 `json:"maker_fee"`
	TakerFee    float64 `json:"taker_fee"`
	Description string  `json:"description"`
}

type FraudLog struct {
	ID          int64     `json:"id"`
	UserIds     string    `json:"user_ids"`
	FraudType   string    `json:"fraud_type"`
	Description string    `json:"description"`
	Evidence    string    `json:"evidence"`
	Action      string    `json:"action"`
	AdminNote   string    `json:"admin_note"`
	CreatedAt   time.Time `json:"created_at"`
}

type KycDocument struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	DocType   string    `json:"doc_type"`
	FilePath  string    `json:"file_path"`
	Status    string    `json:"status"`
	AdminNote string    `json:"admin_note"`
	CreatedAt time.Time `json:"created_at"`
}

type KycProfile struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	FirstName   string    `json:"first_name"`
	LastName    string    `json:"last_name"`
	DateOfBirth string    `json:"date_of_birth"`
	Phone       string    `json:"phone"`
	Address     string    `json:"address"`
	Ward        string    `json:"ward"`
	District    string    `json:"district"`
	City        string    `json:"city"`
	PostalCode  string    `json:"postal_code"`
	Country     string    `json:"country"`
	Occupation  string    `json:"occupation"`
	Income      string    `json:"income"`
	TradingExp  string    `json:"trading_exp"`
	Purpose     string    `json:"purpose"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type PlatformSetting struct {
	ID                 int64   `json:"id"`
	DepositFeePercent  float64 `json:"deposit_fee_percent"`
	WithdrawFeePercent float64 `json:"withdraw_fee_percent"`
	MinDeposit         float64 `json:"min_deposit"`
	MaxDeposit         float64 `json:"max_deposit"`
	MinWithdraw        float64 `json:"min_withdraw"`
	MaxWithdraw        float64 `json:"max_withdraw"`
	TradingFeePercent  float64 `json:"trading_fee_percent"`
	KycRequired        bool    `json:"kyc_required"`
}

type Referral struct {
	ID         int64     `json:"id"`
	ReferrerID int64     `json:"referrer_id"`
	RefereeID  int64     `json:"referee_id"`
	Code       string    `json:"code"`
	Tier       int32     `json:"tier"`
	CreatedAt  time.Time `json:"created_at"`
}

type ReferralCode struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	Code       string    `json:"code"`
	IsDefault  bool      `json:"is_default"`
	UsageCount int32     `json:"usage_count"`
	CreatedAt  time.Time `json:"created_at"`
}

type ReferralCommission struct {
	ID         int64     `json:"id"`
	ReferrerID int64     `json:"referrer_id"`
	RefereeID  int64     `json:"referee_id"`
	TradeID    int64     `json:"trade_id"`
	Currency   string    `json:"currency"`
	FeeAmount  float64   `json:"fee_amount"`
	Rate       float64   `json:"rate"`
	Commission float64   `json:"commission"`
	CreatedAt  time.Time `json:"created_at"`
}

type RefreshToken struct {
	ID            int64      `json:"id"`
	UserID        int64      `json:"user_id"`
	TokenHash     string     `json:"token_hash"`
	FamilyID      string     `json:"family_id"`
	ParentID      *int64     `json:"parent_id"`
	UserAgent     string     `json:"user_agent"`
	Ip            string     `json:"ip"`
	IssuedAt      time.Time  `json:"issued_at"`
	ExpiresAt     time.Time  `json:"expires_at"`
	UsedAt        *time.Time `json:"used_at"`
	RevokedAt     *time.Time `json:"revoked_at"`
	RevokedReason string     `json:"revoked_reason"`
}

type User struct {
	ID            int64     `json:"id"`
	Email         string    `json:"email"`
	PasswordHash  string    `json:"password_hash"`
	FullName      string    `json:"full_name"`
	Phone         string    `json:"phone"`
	KycStatus     string    `json:"kyc_status"`
	Is2Fa         bool      `json:"is2_fa"`
	TwoFaSecret   string    `json:"two_fa_secret"`
	Role          string    `json:"role"`
	EmailVerified bool      `json:"email_verified"`
	KycStep       int32     `json:"kyc_step"`
	IsLocked      bool      `json:"is_locked"`
	LockReason    string    `json:"lock_reason"`
	LastLoginIp   string    `json:"last_login_ip"`
	RegisterIp    string    `json:"register_ip"`
	GoogleSub     string    `json:"google_sub"`
	AvatarUrl     string    `json:"avatar_url"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type UserBonu struct {
	ID          int64      `json:"id"`
	UserID      int64      `json:"user_id"`
	PromotionID int64      `json:"promotion_id"`
	DepositID   int64      `json:"deposit_id"`
	BonusAmount float64    `json:"bonus_amount"`
	UsedAmount  float64    `json:"used_amount"`
	Status      string     `json:"status"`
	CreatedAt   time.Time  `json:"created_at"`
	ExpiresAt   *time.Time `json:"expires_at"`
}

type UserTradePair struct {
	ID         int64     `json:"id"`
	User1ID    int64     `json:"user1_id"`
	User2ID    int64     `json:"user2_id"`
	Pair       string    `json:"pair"`
	TradeCount int32     `json:"trade_count"`
	TotalVol   float64   `json:"total_vol"`
	FirstTrade time.Time `json:"first_trade"`
	LastTrade  time.Time `json:"last_trade"`
}

type UserVolume30d struct {
	UserID    int64     `json:"user_id"`
	Volume    float64   `json:"volume"`
	TierLevel int32     `json:"tier_level"`
	UpdatedAt time.Time `json:"updated_at"`
}
