// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"time"
)

type Querier interface {
	CountAuditAll(ctx context.Context, action string) (int64, error)
	CountAuditByUser(ctx context.Context, userID int64) (int64, error)
	CountAuditDeviceForUser(ctx context.Context, arg CountAuditDeviceForUserParams) (int64, error)
	CountCoins(ctx context.Context) (int64, error)
	CountCommissions(ctx context.Context, referrerID int64) (int64, error)
	CountFeeTiers(ctx context.Context) (int64, error)
	CountFraudByTypeUsers(ctx context.Context, arg CountFraudByTypeUsersParams) (int64, error)
	// Existing-flag guard for flagBonusFarming (ignores already-dismissed flags).
	CountFraudByTypeUsersActive(ctx context.Context, arg CountFraudByTypeUsersActiveParams) (int64, error)
	CountFraudLogs(ctx context.Context, search string) (int64, error)
	CountPendingKYCUsers(ctx context.Context) (int64, error)
	// Excludes SYSTEM accounts (infrastructure rows), used for demo-seed gating + stats.
	CountRealUsers(ctx context.Context) (int64, error)
	CountReferees(ctx context.Context, referrerID int64) (int64, error)
	CountUsersAdmin(ctx context.Context, search string) (int64, error)
	CountUsersByKYCStatus(ctx context.Context, kycStatus string) (int64, error)
	CountUsersExclSystem(ctx context.Context, search string) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (CreateAuditLogRow, error)
	CreateFraudLog(ctx context.Context, arg CreateFraudLogParams) (CreateFraudLogRow, error)
	CreateKYCDocument(ctx context.Context, arg CreateKYCDocumentParams) (CreateKYCDocumentRow, error)
	CreateKYCProfile(ctx context.Context, arg CreateKYCProfileParams) (CreateKYCProfileRow, error)
	CreatePromotion(ctx context.Context, arg CreatePromotionParams) (CreatePromotionRow, error)
	CreateReferral(ctx context.Context, arg CreateReferralParams) (CreateReferralRow, error)
	CreateReferralCode(ctx context.Context, arg CreateReferralCodeParams) (CreateReferralCodeRow, error)
	// Idempotent on trade_id; the conflict path returns the existing row's id.
	CreateReferralCommission(ctx context.Context, arg CreateReferralCommissionParams) (CreateReferralCommissionRow, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserBonus(ctx context.Context, arg CreateUserBonusParams) (CreateUserBonusRow, error)
	// Retention cleanup: drop tokens that are expired or were revoked before cutoff.
	DeleteExpiredRefreshTokens(ctx context.Context, cutoff time.Time) (int64, error)
	FindActivePromotions(ctx context.Context) ([]BonusPromotion, error)
	FindActiveUserBonuses(ctx context.Context, userID int64) ([]UserBonu, error)
	FindAllPromotions(ctx context.Context) ([]BonusPromotion, error)
	FindPromotionByID(ctx context.Context, id int64) (BonusPromotion, error)
	FindUserBonuses(ctx context.Context, userID int64) ([]UserBonu, error)
	GetAPIKeyByKeyID(ctx context.Context, keyID string) (ApiKey, error)
	GetDefaultReferralCode(ctx context.Context, userID int64) (ReferralCode, error)
	GetFeeTierByLevel(ctx context.Context, level int32) (FeeTier, error)
	GetKYCDocumentByUserAndType(ctx context.Context, arg GetKYCDocumentByUserAndTypeParams) (KycDocument, error)
	GetKYCProfileByUser(ctx context.Context, userID int64) (KycProfile, error)
	GetPlatformSettings(ctx context.Context, id int64) (PlatformSetting, error)
	GetReferralByReferee(ctx context.Context, refereeID int64) (Referral, error)
	GetReferralCodeByValue(ctx context.Context, code string) (ReferralCode, error)
	GetReferralCommissionByTrade(ctx context.Context, tradeID int64) (ReferralCommission, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleSub(ctx context.Context, googleSub string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserVolume(ctx context.Context, userID int64) (UserVolume30d, error)
	IncrementReferralUsage(ctx context.Context, id int64) error
	IncrementVolume(ctx context.Context, arg IncrementVolumeParams) error
	InsertCoin(ctx context.Context, arg InsertCoinParams) error
	InsertFeeTier(ctx context.Context, arg InsertFeeTierParams) error
	ListAPIKeysByUser(ctx context.Context, userID int64) ([]ApiKey, error)
	// An empty @action disables the action filter.
	ListAuditAll(ctx context.Context, arg ListAuditAllParams) ([]AuditLog, error)
	ListAuditByUser(ctx context.Context, arg ListAuditByUserParams) ([]AuditLog, error)
	ListCommissions(ctx context.Context, arg ListCommissionsParams) ([]ReferralCommission, error)
	ListFeeTiers(ctx context.Context) ([]FeeTier, error)
	// An empty @search disables the free-text filter.
	ListFraudLogs(ctx context.Context, arg ListFraudLogsParams) ([]FraudLog, error)
	ListKYCDocumentsByUser(ctx context.Context, userID int64) ([]KycDocument, error)
	// kyc.FindPendingUsers: users awaiting review, newest activity first.
	ListPendingKYCUsers(ctx context.Context, arg ListPendingKYCUsersParams) ([]User, error)
	ListReferees(ctx context.Context, arg ListRefereesParams) ([]Referral, error)
	// admin.GetUsers: full list (SYSTEM included), optional search.
	ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]User, error)
	// userRepo.FindPaginated: customer list (SYSTEM hidden), optional email/name search.
	ListUsersExclSystem(ctx context.Context, arg ListUsersExclSystemParams) ([]User, error)
	MarkRefreshTokenUsed(ctx context.Context, id int64) error
	PruneAuditOlderThan(ctx context.Context, createdAt time.Time) (int64, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error
	RevokeRefreshTokenByID(ctx context.Context, arg RevokeRefreshTokenByIDParams) error
	RevokeRefreshTokenFamily(ctx context.Context, arg RevokeRefreshTokenFamilyParams) error
	RevokeRefreshTokensByUser(ctx context.Context, arg RevokeRefreshTokensByUserParams) error
	SumActiveBonus(ctx context.Context, userID int64) (float64, error)
	SumCommissionByUser(ctx context.Context, referrerID int64) (float64, error)
	UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) error
	UpdateAllKYCDocumentsStatus(ctx context.Context, arg UpdateAllKYCDocumentsStatusParams) error
	UpdateFraudAction(ctx context.Context, arg UpdateFraudActionParams) error
	UpdateKYCDocumentStatus(ctx context.Context, arg UpdateKYCDocumentStatusParams) error
	UpdateKYCProfile(ctx context.Context, arg UpdateKYCProfileParams) error
	UpdatePromotion(ctx context.Context, arg UpdatePromotionParams) error
	// Full-row update (mirrors gorm Save). id/created_at are immutable.
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserBonus(ctx context.Context, arg UpdateUserBonusParams) error
	UpdateUserKYCStatus(ctx context.Context, arg UpdateUserKYCStatusParams) error
	// Single-row settings (id is always 1). Insert-or-replace all fields.
	UpsertPlatformSettings(ctx context.Context, arg UpsertPlatformSettingsParams) error
	// Increment the cross-user trade counter for (user1<user2, pair); the conflict
	// path bumps trade_count and adds the volume. Returns the post-update counters
	// the fraud detector thresholds against.
	UpsertUserTradePair(ctx context.Context, arg UpsertUserTradePairParams) (UpsertUserTradePairRow, error)
	UpsertVolume(ctx context.Context, arg UpsertVolumeParams) error
	// admin chart: new users per day since a cutoff.
	UserGrowthDaily(ctx context.Context, createdAt time.Time) ([]UserGrowthDailyRow, error)
}

var _ Querier = (*Queries)(nil)
