// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: referral.sql

package sqlc

import (
	"context"
	"time"
)

const countCommissions = `-- name: CountCommissions :one
SELECT count(*) FROM referral_commissions WHERE referrer_id = $1
`

func (q *Queries) CountCommissions(ctx context.Context, referrerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCommissions, referrerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReferees = `-- name: CountReferees :one
SELECT count(*) FROM referrals WHERE referrer_id = $1
`

func (q *Queries) CountReferees(ctx context.Context, referrerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countReferees, referrerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReferral = `-- name: CreateReferral :one
INSERT INTO referrals (referrer_id, referee_id, code, tier)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at
`

type CreateReferralParams struct {
	ReferrerID int64  `json:"referrer_id"`
	RefereeID  int64  `json:"referee_id"`
	Code       string `json:"code"`
	Tier       int32  `json:"tier"`
}

type CreateReferralRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateReferral(ctx context.Context, arg CreateReferralParams) (CreateReferralRow, error) {
	row := q.db.QueryRow(ctx, createReferral,
		arg.ReferrerID,
		arg.RefereeID,
		arg.Code,
		arg.Tier,
	)
	var i CreateReferralRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createReferralCode = `-- name: CreateReferralCode :one
INSERT INTO referral_codes (user_id, code, is_default, usage_count)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at
`

type CreateReferralCodeParams struct {
	UserID     int64  `json:"user_id"`
	Code       string `json:"code"`
	IsDefault  bool   `json:"is_default"`
	UsageCount int32  `json:"usage_count"`
}

type CreateReferralCodeRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateReferralCode(ctx context.Context, arg CreateReferralCodeParams) (CreateReferralCodeRow, error) {
	row := q.db.QueryRow(ctx, createReferralCode,
		arg.UserID,
		arg.Code,
		arg.IsDefault,
		arg.UsageCount,
	)
	var i CreateReferralCodeRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createReferralCommission = `-- name: CreateReferralCommission :one
INSERT INTO referral_commissions (referrer_id, referee_id, trade_id, currency, fee_amount, rate, commission)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (trade_id) DO UPDATE SET trade_id = referral_commissions.trade_id
RETURNING id, created_at
`

type CreateReferralCommissionParams struct {
	ReferrerID int64   `json:"referrer_id"`
	RefereeID  int64   `json:"referee_id"`
	TradeID    int64   `json:"trade_id"`
	Currency   string  `json:"currency"`
	FeeAmount  float64 `json:"fee_amount"`
	Rate       float64 `json:"rate"`
	Commission float64 `json:"commission"`
}

type CreateReferralCommissionRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

// Idempotent on trade_id; the conflict path returns the existing row's id.
func (q *Queries) CreateReferralCommission(ctx context.Context, arg CreateReferralCommissionParams) (CreateReferralCommissionRow, error) {
	row := q.db.QueryRow(ctx, createReferralCommission,
		arg.ReferrerID,
		arg.RefereeID,
		arg.TradeID,
		arg.Currency,
		arg.FeeAmount,
		arg.Rate,
		arg.Commission,
	)
	var i CreateReferralCommissionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getDefaultReferralCode = `-- name: GetDefaultReferralCode :one
SELECT id, user_id, code, is_default, usage_count, created_at FROM referral_codes WHERE user_id = $1 AND is_default = true
`

func (q *Queries) GetDefaultReferralCode(ctx context.Context, userID int64) (ReferralCode, error) {
	row := q.db.QueryRow(ctx, getDefaultReferralCode, userID)
	var i ReferralCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.IsDefault,
		&i.UsageCount,
		&i.CreatedAt,
	)
	return i, err
}

const getReferralByReferee = `-- name: GetReferralByReferee :one
SELECT id, referrer_id, referee_id, code, tier, created_at FROM referrals WHERE referee_id = $1
`

func (q *Queries) GetReferralByReferee(ctx context.Context, refereeID int64) (Referral, error) {
	row := q.db.QueryRow(ctx, getReferralByReferee, refereeID)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.ReferrerID,
		&i.RefereeID,
		&i.Code,
		&i.Tier,
		&i.CreatedAt,
	)
	return i, err
}

const getReferralCodeByValue = `-- name: GetReferralCodeByValue :one
SELECT id, user_id, code, is_default, usage_count, created_at FROM referral_codes WHERE code = $1
`

func (q *Queries) GetReferralCodeByValue(ctx context.Context, code string) (ReferralCode, error) {
	row := q.db.QueryRow(ctx, getReferralCodeByValue, code)
	var i ReferralCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.IsDefault,
		&i.UsageCount,
		&i.CreatedAt,
	)
	return i, err
}

const getReferralCommissionByTrade = `-- name: GetReferralCommissionByTrade :one
SELECT id, referrer_id, referee_id, trade_id, currency, fee_amount, rate, commission, created_at
FROM referral_commissions WHERE trade_id = $1
`

func (q *Queries) GetReferralCommissionByTrade(ctx context.Context, tradeID int64) (ReferralCommission, error) {
	row := q.db.QueryRow(ctx, getReferralCommissionByTrade, tradeID)
	var i ReferralCommission
	err := row.Scan(
		&i.ID,
		&i.ReferrerID,
		&i.RefereeID,
		&i.TradeID,
		&i.Currency,
		&i.FeeAmount,
		&i.Rate,
		&i.Commission,
		&i.CreatedAt,
	)
	return i, err
}

const incrementReferralUsage = `-- name: IncrementReferralUsage :exec
UPDATE referral_codes SET usage_count = usage_count + 1 WHERE id = $1
`

func (q *Queries) IncrementReferralUsage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementReferralUsage, id)
	return err
}

const listCommissions = `-- name: ListCommissions :many
SELECT id, referrer_id, referee_id, trade_id, currency, fee_amount, rate, commission, created_at
FROM referral_commissions WHERE referrer_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListCommissionsParams struct {
	ReferrerID int64 `json:"referrer_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListCommissions(ctx context.Context, arg ListCommissionsParams) ([]ReferralCommission, error) {
	rows, err := q.db.Query(ctx, listCommissions, arg.ReferrerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReferralCommission{}
	for rows.Next() {
		var i ReferralCommission
		if err := rows.Scan(
			&i.ID,
			&i.ReferrerID,
			&i.RefereeID,
			&i.TradeID,
			&i.Currency,
			&i.FeeAmount,
			&i.Rate,
			&i.Commission,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferees = `-- name: ListReferees :many
SELECT id, referrer_id, referee_id, code, tier, created_at
FROM referrals WHERE referrer_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListRefereesParams struct {
	ReferrerID int64 `json:"referrer_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListReferees(ctx context.Context, arg ListRefereesParams) ([]Referral, error) {
	rows, err := q.db.Query(ctx, listReferees, arg.ReferrerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Referral{}
	for rows.Next() {
		var i Referral
		if err := rows.Scan(
			&i.ID,
			&i.ReferrerID,
			&i.RefereeID,
			&i.Code,
			&i.Tier,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumCommissionByUser = `-- name: SumCommissionByUser :one
SELECT COALESCE(SUM(commission), 0)::numeric FROM referral_commissions WHERE referrer_id = $1
`

func (q *Queries) SumCommissionByUser(ctx context.Context, referrerID int64) (float64, error) {
	row := q.db.QueryRow(ctx, sumCommissionByUser, referrerID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}
