// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package sqlc

import (
	"context"
	"time"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, family_id, parent_id, user_agent, ip, issued_at, expires_at, revoked_reason)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type CreateRefreshTokenParams struct {
	UserID        int64     `json:"user_id"`
	TokenHash     string    `json:"token_hash"`
	FamilyID      string    `json:"family_id"`
	ParentID      *int64    `json:"parent_id"`
	UserAgent     string    `json:"user_agent"`
	Ip            string    `json:"ip"`
	IssuedAt      time.Time `json:"issued_at"`
	ExpiresAt     time.Time `json:"expires_at"`
	RevokedReason string    `json:"revoked_reason"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (int64, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.FamilyID,
		arg.ParentID,
		arg.UserAgent,
		arg.Ip,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.RevokedReason,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM refresh_tokens
WHERE expires_at < $1 OR (revoked_at IS NOT NULL AND revoked_at < $1)
`

// Retention cleanup: drop tokens that are expired or were revoked before cutoff.
func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, family_id, parent_id, user_agent, ip, issued_at, expires_at, used_at, revoked_at, revoked_reason
FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ParentID,
		&i.UserAgent,
		&i.Ip,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :exec
UPDATE refresh_tokens SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markRefreshTokenUsed, id)
	return err
}

const revokeRefreshTokenByID = `-- name: RevokeRefreshTokenByID :exec
UPDATE refresh_tokens SET revoked_at = now(), revoked_reason = $2 WHERE id = $1
`

type RevokeRefreshTokenByIDParams struct {
	ID            int64  `json:"id"`
	RevokedReason string `json:"revoked_reason"`
}

func (q *Queries) RevokeRefreshTokenByID(ctx context.Context, arg RevokeRefreshTokenByIDParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenByID, arg.ID, arg.RevokedReason)
	return err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE refresh_tokens SET revoked_at = now(), revoked_reason = $2
WHERE family_id = $1 AND revoked_at IS NULL
`

type RevokeRefreshTokenFamilyParams struct {
	FamilyID      string `json:"family_id"`
	RevokedReason string `json:"revoked_reason"`
}

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, arg RevokeRefreshTokenFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, arg.FamilyID, arg.RevokedReason)
	return err
}

const revokeRefreshTokensByUser = `-- name: RevokeRefreshTokensByUser :exec
UPDATE refresh_tokens SET revoked_at = now(), revoked_reason = $2
WHERE user_id = $1 AND revoked_at IS NULL
`

type RevokeRefreshTokensByUserParams struct {
	UserID        int64  `json:"user_id"`
	RevokedReason string `json:"revoked_reason"`
}

func (q *Queries) RevokeRefreshTokensByUser(ctx context.Context, arg RevokeRefreshTokensByUserParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokensByUser, arg.UserID, arg.RevokedReason)
	return err
}
