// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings_coins.sql

package sqlc

import (
	"context"
)

const countCoins = `-- name: CountCoins :one
SELECT count(*) FROM coins
`

func (q *Queries) CountCoins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCoins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPlatformSettings = `-- name: GetPlatformSettings :one
SELECT id, deposit_fee_percent, withdraw_fee_percent, min_deposit, max_deposit, min_withdraw, max_withdraw, trading_fee_percent, kyc_required
FROM platform_settings WHERE id = $1
`

func (q *Queries) GetPlatformSettings(ctx context.Context, id int64) (PlatformSetting, error) {
	row := q.db.QueryRow(ctx, getPlatformSettings, id)
	var i PlatformSetting
	err := row.Scan(
		&i.ID,
		&i.DepositFeePercent,
		&i.WithdrawFeePercent,
		&i.MinDeposit,
		&i.MaxDeposit,
		&i.MinWithdraw,
		&i.MaxWithdraw,
		&i.TradingFeePercent,
		&i.KycRequired,
	)
	return i, err
}

const insertCoin = `-- name: InsertCoin :exec
INSERT INTO coins (symbol, name, coin_gecko_id, bybit_symbol, icon_url, is_active, sort_order, asset_type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (symbol) DO NOTHING
`

type InsertCoinParams struct {
	Symbol      string `json:"symbol"`
	Name        string `json:"name"`
	CoinGeckoID string `json:"coin_gecko_id"`
	BybitSymbol string `json:"bybit_symbol"`
	IconUrl     string `json:"icon_url"`
	IsActive    bool   `json:"is_active"`
	SortOrder   int32  `json:"sort_order"`
	AssetType   string `json:"asset_type"`
}

func (q *Queries) InsertCoin(ctx context.Context, arg InsertCoinParams) error {
	_, err := q.db.Exec(ctx, insertCoin,
		arg.Symbol,
		arg.Name,
		arg.CoinGeckoID,
		arg.BybitSymbol,
		arg.IconUrl,
		arg.IsActive,
		arg.SortOrder,
		arg.AssetType,
	)
	return err
}

const upsertPlatformSettings = `-- name: UpsertPlatformSettings :exec
INSERT INTO platform_settings (id, deposit_fee_percent, withdraw_fee_percent, min_deposit, max_deposit, min_withdraw, max_withdraw, trading_fee_percent, kyc_required)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET
    deposit_fee_percent = EXCLUDED.deposit_fee_percent,
    withdraw_fee_percent = EXCLUDED.withdraw_fee_percent,
    min_deposit = EXCLUDED.min_deposit,
    max_deposit = EXCLUDED.max_deposit,
    min_withdraw = EXCLUDED.min_withdraw,
    max_withdraw = EXCLUDED.max_withdraw,
    trading_fee_percent = EXCLUDED.trading_fee_percent,
    kyc_required = EXCLUDED.kyc_required
`

type UpsertPlatformSettingsParams struct {
	ID                 int64   `json:"id"`
	DepositFeePercent  float64 `json:"deposit_fee_percent"`
	WithdrawFeePercent float64 `json:"withdraw_fee_percent"`
	MinDeposit         float64 `json:"min_deposit"`
	MaxDeposit         float64 `json:"max_deposit"`
	MinWithdraw        float64 `json:"min_withdraw"`
	MaxWithdraw        float64 `json:"max_withdraw"`
	TradingFeePercent  float64 `json:"trading_fee_percent"`
	KycRequired        bool    `json:"kyc_required"`
}

// Single-row settings (id is always 1). Insert-or-replace all fields.
func (q *Queries) UpsertPlatformSettings(ctx context.Context, arg UpsertPlatformSettingsParams) error {
	_, err := q.db.Exec(ctx, upsertPlatformSettings,
		arg.ID,
		arg.DepositFeePercent,
		arg.WithdrawFeePercent,
		arg.MinDeposit,
		arg.MaxDeposit,
		arg.MinWithdraw,
		arg.MaxWithdraw,
		arg.TradingFeePercent,
		arg.KycRequired,
	)
	return err
}
