// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"
)

const countPendingKYCUsers = `-- name: CountPendingKYCUsers :one
SELECT count(*) FROM users WHERE kyc_status = 'PENDING'
`

func (q *Queries) CountPendingKYCUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingKYCUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRealUsers = `-- name: CountRealUsers :one
SELECT count(*) FROM users WHERE role <> 'SYSTEM'
`

// Excludes SYSTEM accounts (infrastructure rows), used for demo-seed gating + stats.
func (q *Queries) CountRealUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRealUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersAdmin = `-- name: CountUsersAdmin :one
SELECT count(*)
FROM users
WHERE ($1::text = '' OR email ILIKE '%' || $1::text || '%' OR full_name ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountUsersAdmin(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersAdmin, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByKYCStatus = `-- name: CountUsersByKYCStatus :one
SELECT count(*) FROM users WHERE kyc_status = $1
`

func (q *Queries) CountUsersByKYCStatus(ctx context.Context, kycStatus string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByKYCStatus, kycStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersExclSystem = `-- name: CountUsersExclSystem :one
SELECT count(*)
FROM users
WHERE role <> 'SYSTEM'
  AND ($1::text = '' OR email ILIKE '%' || $1::text || '%' OR full_name ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountUsersExclSystem(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersExclSystem, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, full_name, phone, kyc_status, is2_fa, two_fa_secret, role, email_verified, kyc_step, is_locked, lock_reason, last_login_ip, register_ip, google_sub, avatar_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, email, password_hash, full_name, phone, kyc_status, is2_fa, two_fa_secret, role, email_verified, kyc_step, is_locked, lock_reason, last_login_ip, register_ip, google_sub, avatar_url, created_at, updated_at
`

type CreateUserParams struct {
	Email         string `json:"email"`
	PasswordHash  string `json:"password_hash"`
	FullName      string `json:"full_name"`
	Phone         string `json:"phone"`
	KycStatus     string `json:"kyc_status"`
	Is2Fa         bool   `json:"is2_fa"`
	TwoFaSecret   string `json:"two_fa_secret"`
	Role          string `json:"role"`
	EmailVerified bool   `json:"email_verified"`
	KycStep       int32  `json:"kyc_step"`
	IsLocked      bool   `json:"is_locked"`
	LockReason    string `json:"lock_reason"`
	LastLoginIp   string `json:"last_login_ip"`
	RegisterIp    string `json:"register_ip"`
	GoogleSub     string `json:"google_sub"`
	AvatarUrl     string `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Phone,
		arg.KycStatus,
		arg.Is2Fa,
		arg.TwoFaSecret,
		arg.Role,
		arg.EmailVerified,
		arg.KycStep,
		arg.IsLocked,
		arg.LockReason,
		arg.LastLoginIp,
		arg.RegisterIp,
		arg.GoogleSub,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.KycStatus,
		&i.Is2Fa,
		&i.TwoFaSecret,
		&i.Role,
		&i.EmailVerified,
		&i.KycStep,
		&i.IsLocked,
		&i.LockReason,
		&i.LastLoginIp,
		&i.RegisterIp,
		&i.GoogleSub,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name, phone, kyc_status, is2_fa, two_fa_secret, role, email_verified, kyc_step, is_locked, lock_reason, last_login_ip, register_ip, google_sub, avatar_url, created_at, updated_at
FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.KycStatus,
		&i.Is2Fa,
		&i.TwoFaSecret,
		&i.Role,
		&i.EmailVerified,
		&i.KycStep,
		&i.IsLocked,
		&i.LockReason,
		&i.LastLoginIp,
		&i.RegisterIp,
		&i.GoogleSub,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleSub = `-- name: GetUserByGoogleSub :one
SELECT id, email, password_hash, full_name, phone, kyc_status, is2_fa, two_fa_secret, role, email_verified, kyc_step, is_locked, lock_reason, last_login_ip, register_ip, google_sub, avatar_url, created_at, updated_at
FROM users WHERE google_sub = $1
`

func (q *Queries) GetUserByGoogleSub(ctx context.Context, googleSub string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSub, googleSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.KycStatus,
		&i.Is2Fa,
		&i.TwoFaSecret,
		&i.Role,
		&i.EmailVerified,
		&i.KycStep,
		&i.IsLocked,
		&i.LockReason,
		&i.LastLoginIp,
		&i.RegisterIp,
		&i.GoogleSub,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, full_name, phone, kyc_status, is2_fa, two_fa_secret, role, email_verified, kyc_step, is_locked, lock_reason, last_login_ip, register_ip, google_sub, avatar_url, created_at, updated_at
FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.KycStatus,
		&i.Is2Fa,
		&i.TwoFaSecret,
		&i.Role,
		&i.EmailVerified,
		&i.KycStep,
		&i.IsLocked,
		&i.LockReason,
		&i.LastLoginIp,
		&i.RegisterIp,
		&i.GoogleSub,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingKYCUsers = `-- name: ListPendingKYCUsers :many
SELECT id, email, password_hash, full_name, phone, kyc_status, is2_fa, two_fa_secret, role, email_verified, kyc_step, is_locked, lock_reason, last_login_ip, register_ip, google_sub, avatar_url, created_at, updated_at
FROM users
WHERE kyc_status = 'PENDING'
ORDER BY updated_at DESC
LIMIT $2 OFFSET $1
`

type ListPendingKYCUsersParams struct {
	Off int32 `json:"off"`
	Lim int32 `json:"lim"`
}

// kyc.FindPendingUsers: users awaiting review, newest activity first.
func (q *Queries) ListPendingKYCUsers(ctx context.Context, arg ListPendingKYCUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listPendingKYCUsers, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.Phone,
			&i.KycStatus,
			&i.Is2Fa,
			&i.TwoFaSecret,
			&i.Role,
			&i.EmailVerified,
			&i.KycStep,
			&i.IsLocked,
			&i.LockReason,
			&i.LastLoginIp,
			&i.RegisterIp,
			&i.GoogleSub,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersAdmin = `-- name: ListUsersAdmin :many
SELECT id, email, password_hash, full_name, phone, kyc_status, is2_fa, two_fa_secret, role, email_verified, kyc_step, is_locked, lock_reason, last_login_ip, register_ip, google_sub, avatar_url, created_at, updated_at
FROM users
WHERE ($1::text = '' OR email ILIKE '%' || $1::text || '%' OR full_name ILIKE '%' || $1::text || '%')
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListUsersAdminParams struct {
	Search string `json:"search"`
	Off    int32  `json:"off"`
	Lim    int32  `json:"lim"`
}

// admin.GetUsers: full list (SYSTEM included), optional search.
func (q *Queries) ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersAdmin, arg.Search, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.Phone,
			&i.KycStatus,
			&i.Is2Fa,
			&i.TwoFaSecret,
			&i.Role,
			&i.EmailVerified,
			&i.KycStep,
			&i.IsLocked,
			&i.LockReason,
			&i.LastLoginIp,
			&i.RegisterIp,
			&i.GoogleSub,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersExclSystem = `-- name: ListUsersExclSystem :many
SELECT id, email, password_hash, full_name, phone, kyc_status, is2_fa, two_fa_secret, role, email_verified, kyc_step, is_locked, lock_reason, last_login_ip, register_ip, google_sub, avatar_url, created_at, updated_at
FROM users
WHERE role <> 'SYSTEM'
  AND ($1::text = '' OR email ILIKE '%' || $1::text || '%' OR full_name ILIKE '%' || $1::text || '%')
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListUsersExclSystemParams struct {
	Search string `json:"search"`
	Off    int32  `json:"off"`
	Lim    int32  `json:"lim"`
}

// userRepo.FindPaginated: customer list (SYSTEM hidden), optional email/name search.
func (q *Queries) ListUsersExclSystem(ctx context.Context, arg ListUsersExclSystemParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersExclSystem, arg.Search, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.Phone,
			&i.KycStatus,
			&i.Is2Fa,
			&i.TwoFaSecret,
			&i.Role,
			&i.EmailVerified,
			&i.KycStep,
			&i.IsLocked,
			&i.LockReason,
			&i.LastLoginIp,
			&i.RegisterIp,
			&i.GoogleSub,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET
    email = $2, password_hash = $3, full_name = $4, phone = $5, kyc_status = $6,
    is2_fa = $7, two_fa_secret = $8, role = $9, email_verified = $10, kyc_step = $11,
    is_locked = $12, lock_reason = $13, last_login_ip = $14, register_ip = $15,
    google_sub = $16, avatar_url = $17, updated_at = now()
WHERE id = $1
`

type UpdateUserParams struct {
	ID            int64  `json:"id"`
	Email         string `json:"email"`
	PasswordHash  string `json:"password_hash"`
	FullName      string `json:"full_name"`
	Phone         string `json:"phone"`
	KycStatus     string `json:"kyc_status"`
	Is2Fa         bool   `json:"is2_fa"`
	TwoFaSecret   string `json:"two_fa_secret"`
	Role          string `json:"role"`
	EmailVerified bool   `json:"email_verified"`
	KycStep       int32  `json:"kyc_step"`
	IsLocked      bool   `json:"is_locked"`
	LockReason    string `json:"lock_reason"`
	LastLoginIp   string `json:"last_login_ip"`
	RegisterIp    string `json:"register_ip"`
	GoogleSub     string `json:"google_sub"`
	AvatarUrl     string `json:"avatar_url"`
}

// Full-row update (mirrors gorm Save). id/created_at are immutable.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Phone,
		arg.KycStatus,
		arg.Is2Fa,
		arg.TwoFaSecret,
		arg.Role,
		arg.EmailVerified,
		arg.KycStep,
		arg.IsLocked,
		arg.LockReason,
		arg.LastLoginIp,
		arg.RegisterIp,
		arg.GoogleSub,
		arg.AvatarUrl,
	)
	return err
}

const updateUserKYCStatus = `-- name: UpdateUserKYCStatus :exec
UPDATE users SET kyc_status = $2, updated_at = now() WHERE id = $1
`

type UpdateUserKYCStatusParams struct {
	ID        int64  `json:"id"`
	KycStatus string `json:"kyc_status"`
}

func (q *Queries) UpdateUserKYCStatus(ctx context.Context, arg UpdateUserKYCStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserKYCStatus, arg.ID, arg.KycStatus)
	return err
}

const userGrowthDaily = `-- name: UserGrowthDaily :many
SELECT DATE(created_at)::text AS day, count(*) AS count
FROM users
WHERE created_at >= $1
GROUP BY DATE(created_at)
ORDER BY day ASC
`

type UserGrowthDailyRow struct {
	Day   string `json:"day"`
	Count int64  `json:"count"`
}

// admin chart: new users per day since a cutoff.
func (q *Queries) UserGrowthDaily(ctx context.Context, createdAt time.Time) ([]UserGrowthDailyRow, error) {
	rows, err := q.db.Query(ctx, userGrowthDaily, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserGrowthDailyRow{}
	for rows.Next() {
		var i UserGrowthDailyRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
