// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: funding.sql

package sqlc

import (
	"context"
	"time"
)

const countFundingByUser = `-- name: CountFundingByUser :one
SELECT count(*) FROM funding_payments WHERE user_id = $1
`

func (q *Queries) CountFundingByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countFundingByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFundingPayment = `-- name: CreateFundingPayment :one
INSERT INTO funding_payments (position_id, user_id, funding_rate_id, pair, side, notional, rate, amount)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (position_id, funding_rate_id) DO UPDATE SET position_id = funding_payments.position_id
RETURNING id, created_at
`

type CreateFundingPaymentParams struct {
	PositionID    int64   `json:"position_id"`
	UserID        int64   `json:"user_id"`
	FundingRateID int64   `json:"funding_rate_id"`
	Pair          string  `json:"pair"`
	Side          string  `json:"side"`
	Notional      float64 `json:"notional"`
	Rate          float64 `json:"rate"`
	Amount        float64 `json:"amount"`
}

type CreateFundingPaymentRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

// Idempotent on (position_id, funding_rate_id).
func (q *Queries) CreateFundingPayment(ctx context.Context, arg CreateFundingPaymentParams) (CreateFundingPaymentRow, error) {
	row := q.db.QueryRow(ctx, createFundingPayment,
		arg.PositionID,
		arg.UserID,
		arg.FundingRateID,
		arg.Pair,
		arg.Side,
		arg.Notional,
		arg.Rate,
		arg.Amount,
	)
	var i CreateFundingPaymentRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createFundingRate = `-- name: CreateFundingRate :one
INSERT INTO funding_rates (pair, rate, index_price, mark_price, interval, settled_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (pair, settled_at) DO UPDATE SET pair = funding_rates.pair
RETURNING id
`

type CreateFundingRateParams struct {
	Pair       string    `json:"pair"`
	Rate       float64   `json:"rate"`
	IndexPrice float64   `json:"index_price"`
	MarkPrice  float64   `json:"mark_price"`
	Interval   string    `json:"interval"`
	SettledAt  time.Time `json:"settled_at"`
}

// Idempotent on (pair, settled_at): a conflict returns the existing row's id via
// a no-op UPDATE (so the caller always gets an id, matching gorm FirstOrCreate).
func (q *Queries) CreateFundingRate(ctx context.Context, arg CreateFundingRateParams) (int64, error) {
	row := q.db.QueryRow(ctx, createFundingRate,
		arg.Pair,
		arg.Rate,
		arg.IndexPrice,
		arg.MarkPrice,
		arg.Interval,
		arg.SettledAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const fundingHistoryByUser = `-- name: FundingHistoryByUser :many
SELECT id, position_id, user_id, funding_rate_id, pair, side, notional, rate, amount, created_at
FROM funding_payments
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type FundingHistoryByUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FundingHistoryByUser(ctx context.Context, arg FundingHistoryByUserParams) ([]FundingPayment, error) {
	rows, err := q.db.Query(ctx, fundingHistoryByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FundingPayment{}
	for rows.Next() {
		var i FundingPayment
		if err := rows.Scan(
			&i.ID,
			&i.PositionID,
			&i.UserID,
			&i.FundingRateID,
			&i.Pair,
			&i.Side,
			&i.Notional,
			&i.Rate,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestFundingRate = `-- name: LatestFundingRate :one
SELECT id, pair, rate, index_price, mark_price, interval, settled_at, created_at
FROM funding_rates
WHERE pair = $1
ORDER BY settled_at DESC
LIMIT 1
`

func (q *Queries) LatestFundingRate(ctx context.Context, pair string) (FundingRate, error) {
	row := q.db.QueryRow(ctx, latestFundingRate, pair)
	var i FundingRate
	err := row.Scan(
		&i.ID,
		&i.Pair,
		&i.Rate,
		&i.IndexPrice,
		&i.MarkPrice,
		&i.Interval,
		&i.SettledAt,
		&i.CreatedAt,
	)
	return i, err
}

const recentFundingRates = `-- name: RecentFundingRates :many
SELECT id, pair, rate, index_price, mark_price, interval, settled_at, created_at
FROM funding_rates
WHERE pair = $1
ORDER BY settled_at DESC
LIMIT $2
`

type RecentFundingRatesParams struct {
	Pair  string `json:"pair"`
	Limit int32  `json:"limit"`
}

func (q *Queries) RecentFundingRates(ctx context.Context, arg RecentFundingRatesParams) ([]FundingRate, error) {
	rows, err := q.db.Query(ctx, recentFundingRates, arg.Pair, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FundingRate{}
	for rows.Next() {
		var i FundingRate
		if err := rows.Scan(
			&i.ID,
			&i.Pair,
			&i.Rate,
			&i.IndexPrice,
			&i.MarkPrice,
			&i.Interval,
			&i.SettledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
