// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type FundingPayment struct {
	ID            int64     `json:"id"`
	PositionID    int64     `json:"position_id"`
	UserID        int64     `json:"user_id"`
	FundingRateID int64     `json:"funding_rate_id"`
	Pair          string    `json:"pair"`
	Side          string    `json:"side"`
	Notional      float64   `json:"notional"`
	Rate          float64   `json:"rate"`
	Amount        float64   `json:"amount"`
	CreatedAt     time.Time `json:"created_at"`
}

type FundingRate struct {
	ID         int64     `json:"id"`
	Pair       string    `json:"pair"`
	Rate       float64   `json:"rate"`
	IndexPrice float64   `json:"index_price"`
	MarkPrice  float64   `json:"mark_price"`
	Interval   string    `json:"interval"`
	SettledAt  time.Time `json:"settled_at"`
	CreatedAt  time.Time `json:"created_at"`
}

type FuturesPosition struct {
	ID               int64      `json:"id"`
	UserID           int64      `json:"user_id"`
	Pair             string     `json:"pair"`
	Side             string     `json:"side"`
	Leverage         int32      `json:"leverage"`
	EntryPrice       float64    `json:"entry_price"`
	MarkPrice        float64    `json:"mark_price"`
	Size             float64    `json:"size"`
	Margin           float64    `json:"margin"`
	UnrealizedPnL    float64    `json:"unrealized_pn_l"`
	LiquidationPrice float64    `json:"liquidation_price"`
	TakeProfit       float64    `json:"take_profit"`
	StopLoss         float64    `json:"stop_loss"`
	Status           string     `json:"status"`
	CreatedAt        time.Time  `json:"created_at"`
	ClosedAt         *time.Time `json:"closed_at"`
}
