// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: positions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPosition = `-- name: CreatePosition :one
INSERT INTO futures_positions (user_id, pair, side, leverage, entry_price, mark_price, size, margin, unrealized_pn_l, liquidation_price, take_profit, stop_loss, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, user_id, pair, side, leverage, entry_price, mark_price, size, margin, unrealized_pn_l, liquidation_price, take_profit, stop_loss, status, created_at, closed_at
`

type CreatePositionParams struct {
	UserID           int64   `json:"user_id"`
	Pair             string  `json:"pair"`
	Side             string  `json:"side"`
	Leverage         int32   `json:"leverage"`
	EntryPrice       float64 `json:"entry_price"`
	MarkPrice        float64 `json:"mark_price"`
	Size             float64 `json:"size"`
	Margin           float64 `json:"margin"`
	UnrealizedPnL    float64 `json:"unrealized_pn_l"`
	LiquidationPrice float64 `json:"liquidation_price"`
	TakeProfit       float64 `json:"take_profit"`
	StopLoss         float64 `json:"stop_loss"`
	Status           string  `json:"status"`
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) (FuturesPosition, error) {
	row := q.db.QueryRow(ctx, createPosition,
		arg.UserID,
		arg.Pair,
		arg.Side,
		arg.Leverage,
		arg.EntryPrice,
		arg.MarkPrice,
		arg.Size,
		arg.Margin,
		arg.UnrealizedPnL,
		arg.LiquidationPrice,
		arg.TakeProfit,
		arg.StopLoss,
		arg.Status,
	)
	var i FuturesPosition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Pair,
		&i.Side,
		&i.Leverage,
		&i.EntryPrice,
		&i.MarkPrice,
		&i.Size,
		&i.Margin,
		&i.UnrealizedPnL,
		&i.LiquidationPrice,
		&i.TakeProfit,
		&i.StopLoss,
		&i.Status,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const findAllOpenPositions = `-- name: FindAllOpenPositions :many
SELECT id, user_id, pair, side, leverage, entry_price, mark_price, size, margin, unrealized_pn_l, liquidation_price, take_profit, stop_loss, status, created_at, closed_at
FROM futures_positions
WHERE status = 'OPEN'
`

func (q *Queries) FindAllOpenPositions(ctx context.Context) ([]FuturesPosition, error) {
	rows, err := q.db.Query(ctx, findAllOpenPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FuturesPosition{}
	for rows.Next() {
		var i FuturesPosition
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Pair,
			&i.Side,
			&i.Leverage,
			&i.EntryPrice,
			&i.MarkPrice,
			&i.Size,
			&i.Margin,
			&i.UnrealizedPnL,
			&i.LiquidationPrice,
			&i.TakeProfit,
			&i.StopLoss,
			&i.Status,
			&i.CreatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOpenPositionsByUser = `-- name: FindOpenPositionsByUser :many
SELECT id, user_id, pair, side, leverage, entry_price, mark_price, size, margin, unrealized_pn_l, liquidation_price, take_profit, stop_loss, status, created_at, closed_at
FROM futures_positions
WHERE user_id = $1 AND status = 'OPEN'
ORDER BY created_at DESC
`

func (q *Queries) FindOpenPositionsByUser(ctx context.Context, userID int64) ([]FuturesPosition, error) {
	rows, err := q.db.Query(ctx, findOpenPositionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FuturesPosition{}
	for rows.Next() {
		var i FuturesPosition
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Pair,
			&i.Side,
			&i.Leverage,
			&i.EntryPrice,
			&i.MarkPrice,
			&i.Size,
			&i.Margin,
			&i.UnrealizedPnL,
			&i.LiquidationPrice,
			&i.TakeProfit,
			&i.StopLoss,
			&i.Status,
			&i.CreatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPositionByIDForUpdate = `-- name: FindPositionByIDForUpdate :one
SELECT id, user_id, pair, side, leverage, entry_price, mark_price, size, margin, unrealized_pn_l, liquidation_price, take_profit, stop_loss, status, created_at, closed_at
FROM futures_positions
WHERE id = $1 AND status = $2
FOR UPDATE
`

type FindPositionByIDForUpdateParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) FindPositionByIDForUpdate(ctx context.Context, arg FindPositionByIDForUpdateParams) (FuturesPosition, error) {
	row := q.db.QueryRow(ctx, findPositionByIDForUpdate, arg.ID, arg.Status)
	var i FuturesPosition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Pair,
		&i.Side,
		&i.Leverage,
		&i.EntryPrice,
		&i.MarkPrice,
		&i.Size,
		&i.Margin,
		&i.UnrealizedPnL,
		&i.LiquidationPrice,
		&i.TakeProfit,
		&i.StopLoss,
		&i.Status,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const findPositionByUserAndID = `-- name: FindPositionByUserAndID :one
SELECT id, user_id, pair, side, leverage, entry_price, mark_price, size, margin, unrealized_pn_l, liquidation_price, take_profit, stop_loss, status, created_at, closed_at
FROM futures_positions
WHERE id = $1 AND user_id = $2 AND status = $3
`

type FindPositionByUserAndIDParams struct {
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
	Status string `json:"status"`
}

func (q *Queries) FindPositionByUserAndID(ctx context.Context, arg FindPositionByUserAndIDParams) (FuturesPosition, error) {
	row := q.db.QueryRow(ctx, findPositionByUserAndID, arg.ID, arg.UserID, arg.Status)
	var i FuturesPosition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Pair,
		&i.Side,
		&i.Leverage,
		&i.EntryPrice,
		&i.MarkPrice,
		&i.Size,
		&i.Margin,
		&i.UnrealizedPnL,
		&i.LiquidationPrice,
		&i.TakeProfit,
		&i.StopLoss,
		&i.Status,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const findPositionByUserAndIDForUpdate = `-- name: FindPositionByUserAndIDForUpdate :one
SELECT id, user_id, pair, side, leverage, entry_price, mark_price, size, margin, unrealized_pn_l, liquidation_price, take_profit, stop_loss, status, created_at, closed_at
FROM futures_positions
WHERE id = $1 AND user_id = $2 AND status = $3
FOR UPDATE
`

type FindPositionByUserAndIDForUpdateParams struct {
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
	Status string `json:"status"`
}

func (q *Queries) FindPositionByUserAndIDForUpdate(ctx context.Context, arg FindPositionByUserAndIDForUpdateParams) (FuturesPosition, error) {
	row := q.db.QueryRow(ctx, findPositionByUserAndIDForUpdate, arg.ID, arg.UserID, arg.Status)
	var i FuturesPosition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Pair,
		&i.Side,
		&i.Leverage,
		&i.EntryPrice,
		&i.MarkPrice,
		&i.Size,
		&i.Margin,
		&i.UnrealizedPnL,
		&i.LiquidationPrice,
		&i.TakeProfit,
		&i.StopLoss,
		&i.Status,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const findPositionsByUserAndStatus = `-- name: FindPositionsByUserAndStatus :many
SELECT id, user_id, pair, side, leverage, entry_price, mark_price, size, margin, unrealized_pn_l, liquidation_price, take_profit, stop_loss, status, created_at, closed_at
FROM futures_positions
WHERE user_id = $1 AND ($2::text = '' OR status = $2::text)
ORDER BY created_at DESC
`

type FindPositionsByUserAndStatusParams struct {
	UserID int64  `json:"user_id"`
	Status string `json:"status"`
}

// An empty @status disables the status filter.
func (q *Queries) FindPositionsByUserAndStatus(ctx context.Context, arg FindPositionsByUserAndStatusParams) ([]FuturesPosition, error) {
	rows, err := q.db.Query(ctx, findPositionsByUserAndStatus, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FuturesPosition{}
	for rows.Next() {
		var i FuturesPosition
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Pair,
			&i.Side,
			&i.Leverage,
			&i.EntryPrice,
			&i.MarkPrice,
			&i.Size,
			&i.Margin,
			&i.UnrealizedPnL,
			&i.LiquidationPrice,
			&i.TakeProfit,
			&i.StopLoss,
			&i.Status,
			&i.CreatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const savePosition = `-- name: SavePosition :exec
UPDATE futures_positions
SET pair = $2, side = $3, leverage = $4, entry_price = $5, mark_price = $6, size = $7,
    margin = $8, unrealized_pn_l = $9, liquidation_price = $10, take_profit = $11,
    stop_loss = $12, status = $13, closed_at = $14
WHERE id = $1
`

type SavePositionParams struct {
	ID               int64      `json:"id"`
	Pair             string     `json:"pair"`
	Side             string     `json:"side"`
	Leverage         int32      `json:"leverage"`
	EntryPrice       float64    `json:"entry_price"`
	MarkPrice        float64    `json:"mark_price"`
	Size             float64    `json:"size"`
	Margin           float64    `json:"margin"`
	UnrealizedPnL    float64    `json:"unrealized_pn_l"`
	LiquidationPrice float64    `json:"liquidation_price"`
	TakeProfit       float64    `json:"take_profit"`
	StopLoss         float64    `json:"stop_loss"`
	Status           string     `json:"status"`
	ClosedAt         *time.Time `json:"closed_at"`
}

func (q *Queries) SavePosition(ctx context.Context, arg SavePositionParams) error {
	_, err := q.db.Exec(ctx, savePosition,
		arg.ID,
		arg.Pair,
		arg.Side,
		arg.Leverage,
		arg.EntryPrice,
		arg.MarkPrice,
		arg.Size,
		arg.Margin,
		arg.UnrealizedPnL,
		arg.LiquidationPrice,
		arg.TakeProfit,
		arg.StopLoss,
		arg.Status,
		arg.ClosedAt,
	)
	return err
}

const updateTPSL = `-- name: UpdateTPSL :exec
UPDATE futures_positions
SET take_profit = COALESCE($1::numeric, take_profit),
    stop_loss   = COALESCE($2::numeric, stop_loss)
WHERE id = $3 AND user_id = $4 AND status = 'OPEN'
`

type UpdateTPSLParams struct {
	TakeProfit pgtype.Numeric `json:"take_profit"`
	StopLoss   pgtype.Numeric `json:"stop_loss"`
	ID         int64          `json:"id"`
	UserID     int64          `json:"user_id"`
}

// Update only the provided fields (NULL arg leaves the column unchanged), scoped
// to the owner and only while OPEN.
func (q *Queries) UpdateTPSL(ctx context.Context, arg UpdateTPSLParams) error {
	_, err := q.db.Exec(ctx, updateTPSL,
		arg.TakeProfit,
		arg.StopLoss,
		arg.ID,
		arg.UserID,
	)
	return err
}
