// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CountFundingByUser(ctx context.Context, userID int64) (int64, error)
	// Idempotent on (position_id, funding_rate_id).
	CreateFundingPayment(ctx context.Context, arg CreateFundingPaymentParams) (CreateFundingPaymentRow, error)
	// Idempotent on (pair, settled_at): a conflict returns the existing row's id via
	// a no-op UPDATE (so the caller always gets an id, matching gorm FirstOrCreate).
	CreateFundingRate(ctx context.Context, arg CreateFundingRateParams) (int64, error)
	CreatePosition(ctx context.Context, arg CreatePositionParams) (FuturesPosition, error)
	FindAllOpenPositions(ctx context.Context) ([]FuturesPosition, error)
	FindOpenPositionsByUser(ctx context.Context, userID int64) ([]FuturesPosition, error)
	FindPositionByIDForUpdate(ctx context.Context, arg FindPositionByIDForUpdateParams) (FuturesPosition, error)
	FindPositionByUserAndID(ctx context.Context, arg FindPositionByUserAndIDParams) (FuturesPosition, error)
	FindPositionByUserAndIDForUpdate(ctx context.Context, arg FindPositionByUserAndIDForUpdateParams) (FuturesPosition, error)
	// An empty @status disables the status filter.
	FindPositionsByUserAndStatus(ctx context.Context, arg FindPositionsByUserAndStatusParams) ([]FuturesPosition, error)
	FundingHistoryByUser(ctx context.Context, arg FundingHistoryByUserParams) ([]FundingPayment, error)
	LatestFundingRate(ctx context.Context, pair string) (FundingRate, error)
	RecentFundingRates(ctx context.Context, arg RecentFundingRatesParams) ([]FundingRate, error)
	SavePosition(ctx context.Context, arg SavePositionParams) error
	// Update only the provided fields (NULL arg leaves the column unchanged), scoped
	// to the owner and only while OPEN.
	UpdateTPSL(ctx context.Context, arg UpdateTPSLParams) error
}

var _ Querier = (*Queries)(nil)
