// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Order struct {
	ID           int64     `json:"id"`
	UserID       int64     `json:"user_id"`
	Pair         string    `json:"pair"`
	Side         string    `json:"side"`
	Type         string    `json:"type"`
	Price        float64   `json:"price"`
	StopPrice    float64   `json:"stop_price"`
	Amount       float64   `json:"amount"`
	FilledAmount float64   `json:"filled_amount"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Trade struct {
	ID          int64     `json:"id"`
	Pair        string    `json:"pair"`
	BuyOrderID  int64     `json:"buy_order_id"`
	SellOrderID int64     `json:"sell_order_id"`
	BuyerID     int64     `json:"buyer_id"`
	SellerID    int64     `json:"seller_id"`
	Price       float64   `json:"price"`
	Amount      float64   `json:"amount"`
	Total       float64   `json:"total"`
	BuyerFee    float64   `json:"buyer_fee"`
	SellerFee   float64   `json:"seller_fee"`
	CreatedAt   time.Time `json:"created_at"`
}
