// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"
)

const countOrdersByUser = `-- name: CountOrdersByUser :one
SELECT count(*)
FROM orders
WHERE user_id = $1 AND ($2::text = '' OR status = $2::text)
`

type CountOrdersByUserParams struct {
	UserID int64  `json:"user_id"`
	Status string `json:"status"`
}

func (q *Queries) CountOrdersByUser(ctx context.Context, arg CountOrdersByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByUser, arg.UserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, pair, side, type, price, stop_price, amount, filled_amount, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, pair, side, type, price, stop_price, amount, filled_amount, status, created_at, updated_at
`

type CreateOrderParams struct {
	UserID       int64   `json:"user_id"`
	Pair         string  `json:"pair"`
	Side         string  `json:"side"`
	Type         string  `json:"type"`
	Price        float64 `json:"price"`
	StopPrice    float64 `json:"stop_price"`
	Amount       float64 `json:"amount"`
	FilledAmount float64 `json:"filled_amount"`
	Status       string  `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.Pair,
		arg.Side,
		arg.Type,
		arg.Price,
		arg.StopPrice,
		arg.Amount,
		arg.FilledAmount,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Pair,
		&i.Side,
		&i.Type,
		&i.Price,
		&i.StopPrice,
		&i.Amount,
		&i.FilledAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOpenLimitOrders = `-- name: FindOpenLimitOrders :many
SELECT id, user_id, pair, side, type, price, stop_price, amount, filled_amount, status, created_at, updated_at
FROM orders
WHERE status IN ('OPEN', 'PARTIAL') AND type = 'LIMIT'
`

func (q *Queries) FindOpenLimitOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, findOpenLimitOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Pair,
			&i.Side,
			&i.Type,
			&i.Price,
			&i.StopPrice,
			&i.Amount,
			&i.FilledAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOpenOrders = `-- name: FindOpenOrders :many
SELECT id, user_id, pair, side, type, price, stop_price, amount, filled_amount, status, created_at, updated_at
FROM orders
WHERE user_id = $1 AND status IN ('OPEN', 'PARTIAL')
ORDER BY created_at DESC
`

func (q *Queries) FindOpenOrders(ctx context.Context, userID int64) ([]Order, error) {
	rows, err := q.db.Query(ctx, findOpenOrders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Pair,
			&i.Side,
			&i.Type,
			&i.Price,
			&i.StopPrice,
			&i.Amount,
			&i.FilledAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, pair, side, type, price, stop_price, amount, filled_amount, status, created_at, updated_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Pair,
		&i.Side,
		&i.Type,
		&i.Price,
		&i.StopPrice,
		&i.Amount,
		&i.FilledAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByUserAndID = `-- name: GetOrderByUserAndID :one
SELECT id, user_id, pair, side, type, price, stop_price, amount, filled_amount, status, created_at, updated_at
FROM orders
WHERE id = $1 AND user_id = $2
`

type GetOrderByUserAndIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetOrderByUserAndID(ctx context.Context, arg GetOrderByUserAndIDParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByUserAndID, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Pair,
		&i.Side,
		&i.Type,
		&i.Price,
		&i.StopPrice,
		&i.Amount,
		&i.FilledAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, pair, side, type, price, stop_price, amount, filled_amount, status, created_at, updated_at
FROM orders
WHERE user_id = $1 AND ($2::text = '' OR status = $2::text)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListOrdersByUserParams struct {
	UserID int64  `json:"user_id"`
	Status string `json:"status"`
	Off    int32  `json:"off"`
	Lim    int32  `json:"lim"`
}

// An empty @status disables the status filter.
func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser,
		arg.UserID,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Pair,
			&i.Side,
			&i.Type,
			&i.Price,
			&i.StopPrice,
			&i.Amount,
			&i.FilledAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveOrder = `-- name: SaveOrder :exec
UPDATE orders
SET pair = $2, side = $3, type = $4, price = $5, stop_price = $6, amount = $7,
    filled_amount = $8, status = $9, updated_at = now()
WHERE id = $1
`

type SaveOrderParams struct {
	ID           int64   `json:"id"`
	Pair         string  `json:"pair"`
	Side         string  `json:"side"`
	Type         string  `json:"type"`
	Price        float64 `json:"price"`
	StopPrice    float64 `json:"stop_price"`
	Amount       float64 `json:"amount"`
	FilledAmount float64 `json:"filled_amount"`
	Status       string  `json:"status"`
}

func (q *Queries) SaveOrder(ctx context.Context, arg SaveOrderParams) error {
	_, err := q.db.Exec(ctx, saveOrder,
		arg.ID,
		arg.Pair,
		arg.Side,
		arg.Type,
		arg.Price,
		arg.StopPrice,
		arg.Amount,
		arg.FilledAmount,
		arg.Status,
	)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $1, filled_amount = $2::numeric,
    price = CASE WHEN price = 0 THEN $3::numeric ELSE price END,
    updated_at = now()
WHERE id = $4
`

type UpdateOrderStatusParams struct {
	Status       string  `json:"status"`
	FilledAmount float64 `json:"filled_amount"`
	Price        float64 `json:"price"`
	ID           int64   `json:"id"`
}

// Apply a status/fill change. A MARKET order rests at price 0; seed its price
// from the fill so history shows the executed price.
func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus,
		arg.Status,
		arg.FilledAmount,
		arg.Price,
		arg.ID,
	)
	return err
}
