// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CountOrdersByUser(ctx context.Context, arg CountOrdersByUserParams) (int64, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateTrade(ctx context.Context, arg CreateTradeParams) (CreateTradeRow, error)
	FindOpenLimitOrders(ctx context.Context) ([]Order, error)
	FindOpenOrders(ctx context.Context, userID int64) ([]Order, error)
	GetOrderByID(ctx context.Context, id int64) (Order, error)
	GetOrderByUserAndID(ctx context.Context, arg GetOrderByUserAndIDParams) (Order, error)
	// An empty @status disables the status filter.
	ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error)
	SaveOrder(ctx context.Context, arg SaveOrderParams) error
	// Apply a status/fill change. A MARKET order rests at price 0; seed its price
	// from the fill so history shows the executed price.
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
}

var _ Querier = (*Queries)(nil)
