// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trades.sql

package sqlc

import (
	"context"
	"time"
)

const createTrade = `-- name: CreateTrade :one
INSERT INTO trades (pair, buy_order_id, sell_order_id, buyer_id, seller_id, price, amount, total, buyer_fee, seller_fee)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, created_at
`

type CreateTradeParams struct {
	Pair        string  `json:"pair"`
	BuyOrderID  int64   `json:"buy_order_id"`
	SellOrderID int64   `json:"sell_order_id"`
	BuyerID     int64   `json:"buyer_id"`
	SellerID    int64   `json:"seller_id"`
	Price       float64 `json:"price"`
	Amount      float64 `json:"amount"`
	Total       float64 `json:"total"`
	BuyerFee    float64 `json:"buyer_fee"`
	SellerFee   float64 `json:"seller_fee"`
}

type CreateTradeRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateTrade(ctx context.Context, arg CreateTradeParams) (CreateTradeRow, error) {
	row := q.db.QueryRow(ctx, createTrade,
		arg.Pair,
		arg.BuyOrderID,
		arg.SellOrderID,
		arg.BuyerID,
		arg.SellerID,
		arg.Price,
		arg.Amount,
		arg.Total,
		arg.BuyerFee,
		arg.SellerFee,
	)
	var i CreateTradeRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
