// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/wallet.proto

package walletpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Needed        float64                `protobuf:"fixed64,3,opt,name=needed,proto3" json:"needed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBalanceRequest) Reset() {
	*x = CheckBalanceRequest{}
	mi := &file_proto_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBalanceRequest) ProtoMessage() {}

func (x *CheckBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBalanceRequest.ProtoReflect.Descriptor instead.
func (*CheckBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *CheckBalanceRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckBalanceRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CheckBalanceRequest) GetNeeded() float64 {
	if x != nil {
		return x.Needed
	}
	return 0
}

type CheckBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sufficient    bool                   `protobuf:"varint,1,opt,name=sufficient,proto3" json:"sufficient,omitempty"`
	Available     float64                `protobuf:"fixed64,2,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBalanceResponse) Reset() {
	*x = CheckBalanceResponse{}
	mi := &file_proto_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBalanceResponse) ProtoMessage() {}

func (x *CheckBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBalanceResponse.ProtoReflect.Descriptor instead.
func (*CheckBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *CheckBalanceResponse) GetSufficient() bool {
	if x != nil {
		return x.Sufficient
	}
	return false
}

func (x *CheckBalanceResponse) GetAvailable() float64 {
	if x != nil {
		return x.Available
	}
	return 0
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_proto_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *GetBalanceRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetBalanceRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       float64                `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Locked        float64                `protobuf:"fixed64,2,opt,name=locked,proto3" json:"locked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_proto_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetBalanceResponse) GetLocked() float64 {
	if x != nil {
		return x.Locked
	}
	return 0
}

type DeductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductRequest) Reset() {
	*x = DeductRequest{}
	mi := &file_proto_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductRequest) ProtoMessage() {}

func (x *DeductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductRequest.ProtoReflect.Descriptor instead.
func (*DeductRequest) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *DeductRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeductRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *DeductRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DeductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewBalance    float64                `protobuf:"fixed64,1,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductResponse) Reset() {
	*x = DeductResponse{}
	mi := &file_proto_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductResponse) ProtoMessage() {}

func (x *DeductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductResponse.ProtoReflect.Descriptor instead.
func (*DeductResponse) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *DeductResponse) GetNewBalance() float64 {
	if x != nil {
		return x.NewBalance
	}
	return 0
}

type CreditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditRequest) Reset() {
	*x = CreditRequest{}
	mi := &file_proto_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditRequest) ProtoMessage() {}

func (x *CreditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditRequest.ProtoReflect.Descriptor instead.
func (*CreditRequest) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *CreditRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreditRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreditRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewBalance    float64                `protobuf:"fixed64,1,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditResponse) Reset() {
	*x = CreditResponse{}
	mi := &file_proto_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditResponse) ProtoMessage() {}

func (x *CreditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditResponse.ProtoReflect.Descriptor instead.
func (*CreditResponse) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *CreditResponse) GetNewBalance() float64 {
	if x != nil {
		return x.NewBalance
	}
	return 0
}

type LockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockRequest) Reset() {
	*x = LockRequest{}
	mi := &file_proto_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockRequest) ProtoMessage() {}

func (x *LockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockRequest.ProtoReflect.Descriptor instead.
func (*LockRequest) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *LockRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LockRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *LockRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type LockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockResponse) Reset() {
	*x = LockResponse{}
	mi := &file_proto_wallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockResponse) ProtoMessage() {}

func (x *LockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockResponse.ProtoReflect.Descriptor instead.
func (*LockResponse) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *LockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockRequest) Reset() {
	*x = UnlockRequest{}
	mi := &file_proto_wallet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockRequest) ProtoMessage() {}

func (x *UnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockRequest.ProtoReflect.Descriptor instead.
func (*UnlockRequest) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{10}
}

func (x *UnlockRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnlockRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UnlockRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type UnlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockResponse) Reset() {
	*x = UnlockResponse{}
	mi := &file_proto_wallet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockResponse) ProtoMessage() {}

func (x *UnlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockResponse.ProtoReflect.Descriptor instead.
func (*UnlockResponse) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{11}
}

func (x *UnlockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Delta         float64                `protobuf:"fixed64,3,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBalanceRequest) Reset() {
	*x = UpdateBalanceRequest{}
	mi := &file_proto_wallet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBalanceRequest) ProtoMessage() {}

func (x *UpdateBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBalanceRequest.ProtoReflect.Descriptor instead.
func (*UpdateBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateBalanceRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateBalanceRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateBalanceRequest) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type UpdateBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBalanceResponse) Reset() {
	*x = UpdateBalanceResponse{}
	mi := &file_proto_wallet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBalanceResponse) ProtoMessage() {}

func (x *UpdateBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBalanceResponse.ProtoReflect.Descriptor instead.
func (*UpdateBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateBalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_wallet_proto protoreflect.FileDescriptor

const file_proto_wallet_proto_rawDesc = "" +
	"\n" +
	"\x12proto/wallet.proto\x12\x06wallet\"b\n" +
	"\x13CheckBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06needed\x18\x03 \x01(\x01R\x06needed\"T\n" +
	"\x14CheckBalanceResponse\x12\x1e\n" +
	"\n" +
	"sufficient\x18\x01 \x01(\bR\n" +
	"sufficient\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\x01R\tavailable\"H\n" +
	"\x11GetBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"F\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x01R\abalance\x12\x16\n" +
	"\x06locked\x18\x02 \x01(\x01R\x06locked\"\\\n" +
	"\rDeductRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"1\n" +
	"\x0eDeductResponse\x12\x1f\n" +
	"\vnew_balance\x18\x01 \x01(\x01R\n" +
	"newBalance\"\\\n" +
	"\rCreditRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"1\n" +
	"\x0eCreditResponse\x12\x1f\n" +
	"\vnew_balance\x18\x01 \x01(\x01R\n" +
	"newBalance\"Z\n" +
	"\vLockRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"(\n" +
	"\fLockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\\\n" +
	"\rUnlockRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"*\n" +
	"\x0eUnlockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"a\n" +
	"\x14UpdateBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x01R\x05delta\"1\n" +
	"\x15UpdateBalanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xcb\x03\n" +
	"\rWalletService\x12I\n" +
	"\fCheckBalance\x12\x1b.wallet.CheckBalanceRequest\x1a\x1c.wallet.CheckBalanceResponse\x12C\n" +
	"\n" +
	"GetBalance\x12\x19.wallet.GetBalanceRequest\x1a\x1a.wallet.GetBalanceResponse\x127\n" +
	"\x06Deduct\x12\x15.wallet.DeductRequest\x1a\x16.wallet.DeductResponse\x127\n" +
	"\x06Credit\x12\x15.wallet.CreditRequest\x1a\x16.wallet.CreditResponse\x121\n" +
	"\x04Lock\x12\x13.wallet.LockRequest\x1a\x14.wallet.LockResponse\x127\n" +
	"\x06Unlock\x12\x15.wallet.UnlockRequest\x1a\x16.wallet.UnlockResponse\x12L\n" +
	"\rUpdateBalance\x12\x1c.wallet.UpdateBalanceRequest\x1a\x1d.wallet.UpdateBalanceResponseB*Z(github.com/cryptox/shared/proto/walletpbb\x06proto3"

var (
	file_proto_wallet_proto_rawDescOnce sync.Once
	file_proto_wallet_proto_rawDescData []byte
)

func file_proto_wallet_proto_rawDescGZIP() []byte {
	file_proto_wallet_proto_rawDescOnce.Do(func() {
		file_proto_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wallet_proto_rawDesc), len(file_proto_wallet_proto_rawDesc)))
	})
	return file_proto_wallet_proto_rawDescData
}

var file_proto_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_wallet_proto_goTypes = []any{
	(*CheckBalanceRequest)(nil),   // 0: wallet.CheckBalanceRequest
	(*CheckBalanceResponse)(nil),  // 1: wallet.CheckBalanceResponse
	(*GetBalanceRequest)(nil),     // 2: wallet.GetBalanceRequest
	(*GetBalanceResponse)(nil),    // 3: wallet.GetBalanceResponse
	(*DeductRequest)(nil),         // 4: wallet.DeductRequest
	(*DeductResponse)(nil),        // 5: wallet.DeductResponse
	(*CreditRequest)(nil),         // 6: wallet.CreditRequest
	(*CreditResponse)(nil),        // 7: wallet.CreditResponse
	(*LockRequest)(nil),           // 8: wallet.LockRequest
	(*LockResponse)(nil),          // 9: wallet.LockResponse
	(*UnlockRequest)(nil),         // 10: wallet.UnlockRequest
	(*UnlockResponse)(nil),        // 11: wallet.UnlockResponse
	(*UpdateBalanceRequest)(nil),  // 12: wallet.UpdateBalanceRequest
	(*UpdateBalanceResponse)(nil), // 13: wallet.UpdateBalanceResponse
}
var file_proto_wallet_proto_depIdxs = []int32{
	0,  // 0: wallet.WalletService.CheckBalance:input_type -> wallet.CheckBalanceRequest
	2,  // 1: wallet.WalletService.GetBalance:input_type -> wallet.GetBalanceRequest
	4,  // 2: wallet.WalletService.Deduct:input_type -> wallet.DeductRequest
	6,  // 3: wallet.WalletService.Credit:input_type -> wallet.CreditRequest
	8,  // 4: wallet.WalletService.Lock:input_type -> wallet.LockRequest
	10, // 5: wallet.WalletService.Unlock:input_type -> wallet.UnlockRequest
	12, // 6: wallet.WalletService.UpdateBalance:input_type -> wallet.UpdateBalanceRequest
	1,  // 7: wallet.WalletService.CheckBalance:output_type -> wallet.CheckBalanceResponse
	3,  // 8: wallet.WalletService.GetBalance:output_type -> wallet.GetBalanceResponse
	5,  // 9: wallet.WalletService.Deduct:output_type -> wallet.DeductResponse
	7,  // 10: wallet.WalletService.Credit:output_type -> wallet.CreditResponse
	9,  // 11: wallet.WalletService.Lock:output_type -> wallet.LockResponse
	11, // 12: wallet.WalletService.Unlock:output_type -> wallet.UnlockResponse
	13, // 13: wallet.WalletService.UpdateBalance:output_type -> wallet.UpdateBalanceResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_wallet_proto_init() }
func file_proto_wallet_proto_init() {
	if File_proto_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wallet_proto_rawDesc), len(file_proto_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wallet_proto_goTypes,
		DependencyIndexes: file_proto_wallet_proto_depIdxs,
		MessageInfos:      file_proto_wallet_proto_msgTypes,
	}.Build()
	File_proto_wallet_proto = out.File
	file_proto_wallet_proto_goTypes = nil
	file_proto_wallet_proto_depIdxs = nil
}
